### PR TITLE
Icchen/1967 update image view mode when catalog selection button disabled

### LINKED ISSUE #1967: Update image view mode when catalog selection button is disabled
**Describe the bug**
To be fixed after #1939 is merged. The image view mode remains in catalog selection mode when the catalog selection button is disabled. We may have to update the mode when there's no sources plotted.

**To Reproduce**
1. Open an image and a catalog (catalog button remains disabled) (the image view is in pan mode)
2. Plot some sources (catalog button is enabled, but not active)
3. Click the catalog button (catalog button is active) (the image view is in catalog selection mode)
4. Click reset in the catalog panel to remove all plotted catalog sources (catalog button is disabled, but active) (the image view remains in catalog selection mode)
5. Click the image, the first catalog source is selected

**Expected behavior**
In step 4, catalog button is not active and the image view returns to pan mode.
In step 5, the image view has returned to pan mode, so the first source is not selected.

**Screenshots or videos**
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 103
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: on branch icchen/1826_conditionOfEnablingCatalogSelectionButton

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**
This PR is to resolve #1967.

Two lines are added in `handleResetClick` to set:
1. `ImageViewerLayer` to `RegionMoving` mode
2. `RegionMode` to `MOVING` mode

which updates the image view mode to "pan mode" when catalog selection button is disabled. The result is shown below:

https://user-images.githubusercontent.com/106953609/199252243-751cf0d2-09dc-4028-b599-1ed77d155487.mov

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [X] changelog updated / ~no changelog update needed~
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
this works well as far as I can tell. no regression is observed from e2e tests. 👍

File: src/components/CatalogOverlay/CatalogOverlayComponent.tsx [hunk 1]
```diff
@@ -16,6 +16,8 @@ import {CatalogWidgetStore, CatalogPlotWidgetStoreProps, CatalogPlotType, Catalo
 import {toFixed, ProcessedColumnData} from "utilities";
 import {AbstractCatalogProfileStore, CatalogOverlay, CatalogSystemType} from "models";
 import "./CatalogOverlayComponent.scss";
+import {ImageViewLayer} from "components/ImageView/ImageViewComponent";
+import {RegionMode} from "stores/Frame";
```
Comment (crocka) [inline src/components/CatalogOverlay/CatalogOverlayComponent.tsx:19]: Angus may want us to follow a specific order with these import statements, so maybe first import from external libraries, then our own libraries, and then the scss file.

Comment (I-Chenn) [reply src/components/CatalogOverlay/CatalogOverlayComponent.tsx:19]: Agree, the issue is fixed in commit 598c1c7.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Review by crocka — APPROVED** [review]
