### PR TITLE
strict null check migration 2

### LINKED ISSUE #2592: Re-open File Browser failed when I incompletely enter a path
**Describe the bug**
I click the input path button in the file browser, but I enter 'esc' to close the window. And then, I can't open the file browser again because everything in CARTA is gone.

**To Reproduce**
1. Go to 'File' -> 'Open Image'
2. Click on 'Input directory path'
3. Enter 'esc'
4. Go to  'File' -> 'Open Image' again
5. Everything in CARTA is gone, but CARAT is still running.

**Expected behavior**
Open File Browser

**Screenshots or videos**

**Platform info (please complete the following information):**
 - OS [macOS Sequoia 15.5]: 
 - Browser [chrome]: 
 - Browser version [139.0.7258.155]: 
 - Backend branch [v5.0.3]:
 - Frontend branch [v5.0.3]:

**Additional context**
Console information:

main.e2f97ae4.js:8 [Blueprint] useHotkeys() was used outside of a <HotkeysProvider> context. These hotkeys will not be shown in the hotkeys help dialog.
(anonymous) @ main.e2f97ae4.js:8
main.e2f97ae4.js:8 <== FILE_LIST_RESPONSE [2]
main.e2f97ae4.js:8 e
main.e2f97ae4.js:8 

main.e2f97ae4.js:8 FILE_LIST_REQUEST [3] ==>
main.e2f97ae4.js:8 e
main.e2f97ae4.js:8 

main.e2f97ae4.js:8 TypeError: Cannot read properties of null (reading 'directory')
    at e.render (main.e2f97ae4.js:8:6992895)
    at ps (main.e2f97ae4.js:8:5599913)
    at main.e2f97ae4.js:8:6280078
    at Ts (main.e2f97ae4.js:8:5606678)
    at t.track (main.e2f97ae4.js:8:5610853)
    at e [as render] (main.e2f97ae4.js:8:6280054)
    at Es (main.e2f97ae4.js:8:5011724)
    at Is (main.e2f97ae4.js:8:5011520)
    at _l (main.e2f97ae4.js:8:5055052)
    at Ac (main.e2f97ae4.js:8:5043193)
console.error @ main.e2f97ae4.js:8
main.e2f97ae4.js:8 Uncaught TypeError: Cannot read properties of null (reading 'directory')
    at e.render (main.e2f97ae4.js:8:6992895)
    at ps (main.e2f97ae4.js:8:5599913)
    at main.e2f97ae4.js:8:6280078
    at Ts (main.e2f97ae4.js:8:5606678)
    at t.track (main.e2f97ae4.js:8:5610853)
    at e [as render] (main.e2f97ae4.js:8:6280054)
    at Es (main.e2f97ae4.js:8:5011724)
    at Is (main.e2f97ae4.js:8:5011520)
    at _l (main.e2f97ae4.js:8:5055052)
    at Ac (main.e2f97ae4.js:8:5043193)
main.e2f97ae4.js:8 <== FILE_LIST_RESPONSE [3]
main.e2f97ae4.js:8 e
main.e2f97ae4.js:8

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

This PR is a sequential work of https://github.com/CARTAvis/carta-frontend/issues/2343 following this https://github.com/CARTAvis/carta-frontend/pull/2344. This PR migrates all `Stores`.

This PR closes #2592.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] GitHub Project estimate added

For the pull request:
- [ ] reviewers and assignee added
- [ ] GitHub Project estimate added
- [ ] changelog updated / no changelog update needed
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [ ] protobuf version bumped / no protobuf version bumped needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] corresponding ICD test fix added (`BackendService` changed) / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

### CODE REVIEW

File: src/services/CatalogApiService.ts [hunk 1]
```diff
@@ -148,6 +148,10 @@ export class CatalogApiService {
 
     @action loadCatalog = (fileId: number, catalogInfo: CatalogInfo, headers: CARTA.CatalogHeader[], columnData: Map<number, ProcessedColumnData>, type: CatalogType) => {
         const appStore = AppStore.Instance;
+        if (!appStore.activeFrame) {
+            AppToaster.show(ErrorToast("Please load the image file"));
```
Comment (kswang1029) [inline src/services/CatalogApiService.ts]: "Please load an image file"?

File: src/stores/Frame/FrameStore.ts [hunk 2]
```diff
@@ -679,27 +685,27 @@ export class FrameStore {
...
-                if (isFinite(freqGHz)) {
+                if (freqGHz && isFinite(freqGHz)) {
                     result.spectralString = `Frequency (${this.spectralSystem}): ${formattedFrequency(freqGHz)}`;
                 }
             }
-            // convert frequency to volecity
+            // convert frequency to velocity
             const velocityVal = this.astSpectralTransform(SpectralType.VRAD, SpectralUnit.KMS, this.spectralSystem, freqVal);
-            if (isFinite(velocityVal)) {
+            if (velocityVal && isFinite(velocityVal)) {
```
Comment (kswang1029) [inline src/stores/Frame/FrameStore.ts]: what if velocityVal is 0?

File: src/stores/Frame/FrameStore.ts [hunk 3]
```diff
@@ -679,27 +685,27 @@ export class FrameStore {
...
                 result.velocityString = `Velocity: ${toFixed(velocityVal, 4)} km/s`;
             }
         } else if (spectralType.code === "VRAD") {
             const velocityVal = this.channelInfo.values[channel];
             // convert velocity value to unit in km/s
             if (this.isSpectralCoordinateConvertible && this.spectralAxis?.type.unit !== SPECTRAL_DEFAULT_UNIT.get(SpectralType.VRAD)) {
                 const velocityKMS = this.astSpectralTransform(SpectralType.VRAD, SpectralUnit.KMS, this.spectralSystem, velocityVal);
-                if (isFinite(velocityKMS)) {
+                if (velocityKMS && isFinite(velocityKMS)) {
```
Comment (kswang1029) [inline src/stores/Frame/FrameStore.ts]: what if velocityKMS is 0?

File: src/stores/Frame/FrameStore.ts [hunk 4]
```diff
@@ -2384,20 +2325,20 @@ export class FrameStore {
                 Array.from(SPECTRAL_COORDS_SUPPORTED.keys()).forEach((key: string) => {
                     const value = SPECTRAL_COORDS_SUPPORTED.get(key);
                     const isVolecity = spectralType === SpectralType.VRAD || spectralType === SpectralType.VOPT;
-                    const isValueVolecity = value.type === SpectralType.VRAD || value.type === SpectralType.VOPT;
+                    const isValueVolecity = value?.type === SpectralType.VRAD || value?.type === SpectralType.VOPT;
```
Comment (kswang1029) [inline src/stores/Frame/FrameStore.ts:2328]: typo in isValueVolecity

**Review by kswang1029 — CHANGES_REQUESTED** [review]
If we enable PV preview and keep the pv generator widget and the pv preview widget open, these two widgets remain open if we close the input source image. In v5, once the input source image is closed, these two widgets are closed too.

**Comment by loveluthien** [comment]
> If we enable PV preview and keep the pv generator widget and the pv preview widget open, these two widgets remain open if we close the input source image. In v5, once the input source image is closed, these two widgets are closed too.

This is an independent issue, not related to the strict null check migration

**Review by kswang1029 — APPROVED** [review]
looks fine. let's merge this in and sync updated dev with https://github.com/CARTAvis/carta-frontend/pull/2577. Then I will do another round of testing.
