### PR TITLE
Thchang/2098 spectral matching type selectors improvement

### LINKED ISSUE #2098: do not sync spectral matching reference in the image list settings with the global preferences
**Describe the bug**
Confession: this is a design flaw I made a while ago. 

Currently we can define a new spectral matching reference in the image list settings dialog. When we change it from the default radio velocity to something else, it also changes the global preferences under the scene. As 99% of use case is matching in radio velocity, we should not synchronize the changes here. I realized this bad behavior when I was preparing a CARTA tutorial about spectral matching. In one demo case, I need to match in frequency. But it is hard to see which reference is set when I need to trigger another spectral matching in a new CARTA session. Then my images are matched in frequency which I am aware of and do not want this way. This could introduce confusing and may let users think this is a bug of spectral matching. We should remove this behavior. 

https://user-images.githubusercontent.com/20819712/218371905-0d6844b2-d300-4ebc-9efb-66ed5270e5d0.mov

**Expected behavior**
CARTA initialize the spectral matching reference based on the preferences when a new session is initialized. Then if we simply change the spectral matching reference in the image list widget within the session, it stays what users selected. The preferences remain the same unless users explicitly change it in the preferences dialog. 

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: v3-stable electron app, dev
 - Browser version [e.g. 22]: v3-stable electron app, chrome 109
 - Backend branch [e.g. dev, v3b2 release]: v3-stable, dev
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable, dev

### PR DESCRIPTION
**Pull request by TienHao**
**Description**

Closes #2098: Not to sync the selector of spectral matching type in **Image List Settings** with the one in the global preferences. Modified by adding `spectralMatchingType` in AppStore.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
This works nicely. No regression from e2e tests. 👍

File: src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx [hunk 1]
```diff
@@ -228,13 +212,23 @@ export class PreferenceDialogComponent extends React.Component {
...
-                            <option key={type} value={type}>
-                                {SPECTRAL_TYPE_STRING.get(type)}
-                            </option>
-                        ))}
-                    </HTMLSelect>
+                    <Tooltip2
+                        content={
+                            <span>
+                                Need to apply an instant change? <br />
+                                Please change in the <b>Image List Settings</b>.
```
Comment (YuHsuan-Hwang) [inline src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: I prefer we change it to "Please modify the settings in the Image List Settings."

File: src/stores/AppStore/AppStore.ts [hunk 2]
```diff
@@ -1552,6 +1552,7 @@ export class AppStore {
                 if (this.preferenceStore.checkNewRelease) {
                     await this.checkNewRelease();
                 }
+                this.setSpectralMatchingType(this.preferenceStore.spectralMatchingType);
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: I suggest we move this line before `checkNewRelease()` because fetching data could take time.

File: src/stores/AppStore/AppStore.ts [hunk 3]
```diff
@@ -2712,8 +2713,10 @@ export class AppStore {
         this.setSpectralMatchingEnabled(frame, !frame.spectralReference);
     };
 
-    setSpectralMatchingType = (spectralMatchingType: SpectralType) => {
-        this.preferenceStore.setPreference(PreferenceKeys.GLOBAL_SPECTRAL_MATCHING_TYPE, spectralMatchingType);
+    @observable spectralMatchingType: SpectralType;
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: Perhaps move this line to the upper part of this file for consistency?

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
The feature is working nice. I have some minor suggestions.

File: src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx (hunk 1 above)
Comment (TienHao) [reply src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: Sure, no problem.

File: src/stores/AppStore/AppStore.ts (hunk 2 above)
Comment (TienHao) [reply src/stores/AppStore/AppStore.ts]: Thanks for noting that.

File: src/stores/AppStore/AppStore.ts (hunk 3 above)
Comment (TienHao) [reply src/stores/AppStore/AppStore.ts]: OK

File: src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx (hunk 1 above)
Comment (YuHsuan-Hwang) [reply src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: @TienHao Sorry, I meant changing the second sentence. How about we have just one sentence: "For instant changes, please modify the settings in the Image List Settings."?

Comment (kswang1029) [reply src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: I suggest we don't need that tooltip.

Comment (TienHao) [reply src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: That's OK, the new one is pretty good. Thanks!

Comment (TienHao) [reply src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx]: Sorry, I missed @kswang1029 's comment, just removed it.

**Review by YuHsuan-Hwang — APPROVED** [review]
