### PR TITLE
carli/1758_multiprofile_intensity_unit_conversion

### LINKED ISSUE #1758: spectral profile intensity unit conversion for multi-profile mode
The v3b2 release added the feature of intensity unit conversion for a single profile. This needs to be extended to the multi-profile plot mode. The input image cubes may have different BUNIT headers so the intensity unit conversion needs to consider this. The default reference unit should be the first image with valid convertible unit if there are multiple cubed loaded.

### LINKED ISSUE #1907: unable to convert Jy/beam to K if the spectral axis is VRAD but converting to FREQ is possible
**Describe the bug**
Please download the test images at https://drive.google.com/file/d/1RCy6_ppQ9xk-DdeD1MRgt1Rhu_Mfx0Sx/view?usp=sharing

If the spectral axis defined in the header is VRAD but VRAD to FREQ is still possible, intensity unit conversion from Jy/beam to K should be still allowed. 

**To Reproduce**
1. download the test images
2. load M100_Feather_CO_freq.fits and converting Jy/beam to K is allowed.
3. Sload M100_Feather_CO_velo.fits and try to converting Jy/beam to K. We don't see K is listed but it should as VRAD to FREQ is still possible so the required parameters (freq and beam info) are all there.

**Expected behavior**
If VRAD to FREQ is still possible, we should allow Jy/beam to K conversion.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 103
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by crocka**
**Description**

The pr resolves #1758 and resolves #1907. It tackles three problems. First, the spectral profiles for different frames when matched should convert to the same intensity unit. Second, spectral matching should be avoided if two images do not have intersecting intensity unit. Third, the intensity unit option should only show the ones that are usable for each of the spectrally matched images.

Originally in the ``SpectralProfileWidgetStore``, the ``intensityConversion`` observable is singular, mapping the ``effectiveFrame`` to the selected intensity unit. This is undoubtedly incorrect if we have more than one frame. To solve this issue, the ``intensityConfig`` object was move to ``FrameStore``, and the ``intensityConversion`` is uniquely produced in plotData for each of the frames' profile. To access the frame that correspond to each profile, the frame store of the frame is added to the profile object in the ``profiles`` array in ``SpectralProfileSelectionStore``.

Another problem that the pr solves is that the program should avoid spectral matching when the spectrally matched images do not have common intensity unit. This condition is added to the if-statement in ``setSpectralReference`` function in ``FrameStore`` using the ``getCommonIntensityOptions`` function. The ``getCommonIntensityOptions`` function searches for the common or intersecting intensity unit with 1) a second frame's intensityConfig, if the arguments is a single IntensityConfig, 2) an array of frame's intensityConfig, if the argument is an array rather than a single instance of IntensityConfig. 

The third problem is to allow only the intensity units available for all of the spectrally matched images to show in the intensity option. Knowing that the ``getCommonIntensityOptions`` function finds the intersecting intensity unit, the ``intensityOptions`` in ``SpectralProfileWidgetStore`` simple made use of this function.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [x] changelog updated / ~~no changelog update needed~~
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

File: src/stores/AppStore/AppStore.ts [hunk 1]
```diff
@@ -404,6 +405,7 @@ export class AppStore {
         return this.frames?.map((frame, index) => {
             return {
                 label: index + ": " + frame.filename,
+                frame,
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: We can remove it if it's not used.

File: src/stores/Frame/FrameStore.ts [hunk 2]
```diff
@@ -628,6 +634,29 @@ export class FrameStore {
...
+        let config: IntensityConfig = {nativeIntensityUnit: this.headerUnit};
+        const beams = this.beamAllChannels;
+        if (beams?.length) {
+            config["bmaj"] = beams.map(b => b?.majorAxis);
+            config["bmin"] = beams.map(b => b?.minorAxis);
+            if (this.spectralAxis?.type?.code === "FREQ") {
+                config["freqGHz"] = this.channelInfo?.values.map(x => GetFreqInGHz(this.spectralAxis.type.unit, x));
+            } else if (this.spectralAxis?.type?.code === "VRAD") {
+                config["freqGHz"] = this.channelInfo?.values.map(x => {
+                    const frequency = frequencyFromVelocity(x, this.restFreqStore?.headerRestFreq?.value);
```
Comment (YuHsuan-Hwang) [inline src/stores/Frame/FrameStore.ts]: I think we need to use the user customized rest frequency. Perhaps use `this.restFreqStore?.customRestFreq`.

File: src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts [hunk 3]
```diff
@@ -409,7 +400,17 @@ export class SpectralProfileWidgetStore extends RegionWidgetStore {
...
     @computed get intensityOptions(): string[] {
-        return GetIntensityOptions(this.intensityConfig);
+        const frame = this.effectiveFrame;
+        const isMultiProfileActive = this.profileSelectionStore.activeProfileCategory === MultiProfileCategory.IMAGE;
+
+        const profiles = this.profileSelectionStore.profiles;
+        const displayedFrames = profiles.map(profile => profile.frame);
+
+        if (frame?.spectralReference && isMultiProfileActive) {
+            return frame.commonIntensityUnitWith(displayedFrames);
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts]: I would prefer we add a function like `GetCommonIntensityOptions(configs: IntensityConfig[]): string[]` instead of using `commonIntensityUnitWith`. The function may become simpler, and we can add `frame.intensityConfig` to profiles instead of the entire `frame`.

File: src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts [hunk 4]
```diff
@@ -106,11 +105,8 @@ export class SpectralProfileWidgetStore extends RegionWidgetStore {
         }
     };
 
-    @action setIntensityUnit = (intensityUnitStr: string) => {
-        if (IsIntensitySupported(intensityUnitStr)) {
-            this.intensityUnit = intensityUnitStr;
-            this.intensityConversion = GetIntensityConversion(this.intensityConfig, this.intensityUnit);
-        }
+    @action setStickyIntensityUnit = (intensityUnitStr: string) => {
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts]: Maybe more clear if we rename it as `setMultiProfileIntensityUnit`?

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
Overall the code looks good, and I have some initial comments. Please also update the description in the PR with the new changes.

File: src/stores/AppStore/AppStore.ts (hunk 1 above)
Comment (YuHsuan-Hwang) [reply src/stores/AppStore/AppStore.ts]: @crocka Please also adjust `interface FrameOption`.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@crocka If we just load one image and apply intensity unit conversion, it appears that the function is broken. I can see the ylabel of the spectral plot changes accordingly but not the values. Could you have a look?

**Review by kswang1029 — APPROVED** [review]
looks good now. no regression from e2e tests. 👍

File: src/stores/Frame/FrameStore.ts [hunk 5]
```diff
@@ -604,6 +609,29 @@ export class FrameStore {
...
+        const beams = this.beamAllChannels;
+        if (beams?.length) {
+            config["bmaj"] = beams.map(b => b?.majorAxis);
+            config["bmin"] = beams.map(b => b?.minorAxis);
+            if (this.spectralAxis?.type?.code === "FREQ") {
+                config["freqGHz"] = this.channelInfo?.values.map(x => GetFreqInGHz(this.spectralAxis.type.unit, x));
+            } else if (this.spectralAxis?.type?.code === "VRAD") {
+                config["freqGHz"] = this.channelInfo?.values.map(x => {
+                    const frequency = frequencyFromVelocity(x, this.restFreqStore?.customRestFreq?.value);
+                    return GetFreqInGHz(this.restFreqStore?.headerRestFreq?.unit, frequency);
```
Comment (YuHsuan-Hwang) [inline src/stores/Frame/FrameStore.ts]: Change `headerRestFreq` to `customRestFreq` for consistency. Other than this, the PR is ready for merge. 👍
Please update the change log, thanks.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

**Review by YuHsuan-Hwang — APPROVED** [review]
