### PR TITLE
fixed issue 877, fixed issue 875 #4

### LINKED ISSUE #875: Improvements to catalog file browser
- [ ] Navigating via the file browser to the base directory and then to any sub-directory results in a `.` shown as a directory (might be backend-related, if so please create an issue for @markccchiang)
image
- [x] The catalog information tab always displays `... query string .... ` instead of any meaningful information. 
- [x] Clicking on the refresh button produces an error: `Uncaught TypeError: Cannot read property 'directory' of null` and does not refresh the list.
- [x] When browsing for a second catalog to append, the header from the first selection is shown

### LINKED ISSUE #877: UI improvements of tables in catalog file browser and catalog widget
- [x] disable changing vertical size of a row of the table in catalog file browser
- [x] disable changing vertical size of a row of the tables (both top one and bottom one) in catalog widget
- [x] align texts to cell center vertically in the header table of the catalog widget
- [x] switch to the default font for the header table

Screen Shot 2020-04-17 at 1 38 15 PM
Screen Shot 2020-04-17 at 1 42 02 PM

### PR DESCRIPTION
**Pull request by panchyo0**
1. finished issue 877
2. finished issue 875 #4

### CODE REVIEW

File: src/stores/FileBrowserStore.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export class FileBrowserStore {
         this.selectedHDU = null;
         this.fileInfoExtended = null;
         this.regionFileInfo = null;
+        this.catalogFileInfor = null;
```
Comment (veggiesaurus) [inline src/stores/FileBrowserStore.ts]: prefer `info` instead of `infor`

File: src/components/CatalogOverlay/CatalogOverlayComponent.tsx [hunk 2]
```diff
@@ -203,7 +203,7 @@ export class CatalogOverlayComponent extends React.Component<WidgetProps> {
                 key={columnName} 
                 name={columnName} 
                 cellRenderer={(rowIndex, columnIndex) => (
-                    <Cell key={`cell_${columnIndex}_${rowIndex}`} interactive={true}>{coloumnData[rowIndex]}</Cell>
+                    <Cell style={{lineHeight: "250%"}} key={`cell_${columnIndex}_${rowIndex}`} interactive={true}>{coloumnData[rowIndex]}</Cell>
```
Comment (veggiesaurus) [inline src/components/CatalogOverlay/CatalogOverlayComponent.tsx]: would prefer this to be defined in CSS and for you to just use a `className`, since it is reused elsewhere.

**Review by veggiesaurus — CHANGES_REQUESTED** [review]

**Review by veggiesaurus — APPROVED** [review]
