### PR TITLE
Thchang/improve handling non-standard spectral axis images

### LINKED ISSUE #2225: [Regression] Save Image does not show z-axis info properly for specific image
**Describe the bug**
I found when the users save image, the widget shows the weird information of z-axis.
I have checked with v4b1, the information shows correctly.
e.g.
Screen Shot 2023-08-08 at 12 38 54 PM
However the current dev branch, it shows
e.g. 
Screen Shot 2023-08-08 at 12 39 18 PM

The testing image is "supermosaic.10.fits".
It can be found in the acdc server: /scratch/images
or can be download in [here](https://drive.google.com/drive/folders/1d9IZYp3datnv_QOAXjWfC4CrVUbWU_rh?usp=sharing) (It's about 7GB)

**To Reproduce**
1. Open "supermosaic.10.fits"
2. Go to File > Save Image
3. And you can see the Save Image Range from and to are weird.

**Expected behavior**
Should show as v4b1 behavior (I used Mac Electron Desktop)

**Screenshots or videos**
As I showed in the above

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS 11 Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: Version 114.0.5735.248 (Official Build) (arm64)
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by TienHao**
**Description**

Support **Native/Channel** options in the selector of the spectral coordinate for non-convertible spectral axis images, by adding a new self-defined `NATIVE` spectral type in the `spectralCoordsSupported` of FrameStore for a image with non-supported spectral type. Allow uses to switch between native coordinate value and channel value for spectral coordinate.(Current dev branch only shows native coordinate value for a non-supported spectral type) 

ezgif com-video-to-gif (8)

The reuse of  `SpectralSettingsComponent` in the save image dialogue closes #2225, which displayed **native values** in the Range inputs whereas showed **Channel** in the Range unit selector.

- SpectralSettingsComponent modification
1.showing a Native/Channel options selector for spectral coordinate.
2.displaying the system name for a non-convertible spectral system.(eg. LSR)
3.reused in the ImageSaveComponent

-  code refactoring 
1.replaced property `saveSpectralRange: number[]`([start, end, stride]) in FileBrowserStore with properties `saveSpectralStart/End/Stride`.
2.added custom label for SpectralSettingsComponent to replaced previous Range unit selector.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by kswang1029** [comment]
@TienHao not sure if this is due to the fix here, the input field becomes more aggressive in checking values. When it is 0 and we hit the backspace key, it stays as 0 but if when we see 0 and we enter 10, for example, it works. In other cases, if it is NaN, there is no way back. I would prefer we keep the original way for input fields. 

Screenshot 2023-09-22 at 12 32 35

Another issue here is the input check does not work properly. The following example is the case where I simply switch to channel but the field become red. However, the range is legit.
Screenshot 2023-09-22 at 12 37 07

**Comment by acdo2002** [comment]
I found a regression about "save image".
If you open "M17_SWex.fits" ([link](https://drive.google.com/drive/folders/1Wi1WxXk6gg-aQQXhXTTEN8m8vM4bWMcX?usp=sharing)) and click "save image", then select the "Range Unit" from "Frequency (GHz)" to "Frequency (MHz)", the "Range from" and "Range to" **do not change**
However, they will automatically change in the current dev branch.
Current dev (expect):
Screen Shot 2023-10-02 at 5 49 48 PM
This PR (regression):
Screen Shot 2023-10-02 at 5 51 22 PM

File: src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx [hunk 1]
```diff
@@ -174,23 +161,36 @@ export class ImageSaveComponent extends React.Component {
...
-                                            value={activeFrame && (activeFrame.spectralCoordinate || "")}
-                                            options={spectralCoordinateOptions}
-                                            onChange={(event: React.FormEvent<HTMLSelectElement>) => this.updateSpectralCoordinate(event.currentTarget.value as string)}
-                                        />
-                                        <HTMLSelect
-                                            value={activeFrame && (activeFrame.spectralSystem || "")}
-                                            options={spectralSystemOptions}
-                                            onChange={(event: React.FormEvent<HTMLSelectElement>) => this.updateSpectralSystem(event.currentTarget.value as SpectralSystem)}
+                                    {activeFrame?.spectralSystemsSupported.length > 0 && (
+                                        <SpectralSettingsComponent
```
Comment (YuHsuan-Hwang) [inline src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx]: Good change for reusing `SpectralSettingsComponent` for the UI. 👍

I wonder if we can modify related states in `FrameStore` so that `SpectralSettingsComponent` in general support native <-> channel conversion. This will allow conversion in z profiler, moment generator, PV generator, ... .

image

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx [hunk 2]
```diff
@@ -14,6 +14,7 @@ export class SpectralSettingsComponent extends React.Component<{
     disable: boolean;
     disableChannelOption?: boolean;
     secondaryAxisCursorInfoVisible?: boolean;
+    label?: string;
```
Comment (YuHsuan-Hwang) [inline src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: I suggest we rename it to `customLabel`.

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx [hunk 3]
```diff
@@ -53,7 +54,7 @@ export class SpectralSettingsComponent extends React.Component<{
                     </FormGroup>
                 )}
 
-                <FormGroup label={"System"} inline={true} disabled={disableSystemSetting}>
+                <FormGroup label={this.props.label ? " " : "System"} inline={true} disabled={disableSystemSetting}>
```
Comment (YuHsuan-Hwang) [inline src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: I think we can keep the "System" label here to have consistent design with other widgets.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx (hunk 2 above)
Comment (TienHao) [reply src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: fixed

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx (hunk 3 above)
Comment (TienHao) [reply src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: modified

File: CHANGELOG.md [hunk 4]
```diff
@@ -17,6 +17,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * Fixed bug that the frontend crashes when deleting annotations if the export window is opened ([#2278](https://github.com/CARTAvis/carta-frontend/issues/2278)).
 * Fixed the performance issue when panning images ([#2291](https://github.com/CARTAvis/carta-frontend/issues/2291)).
 * Improved the dragging performance of 'Export Region' widget when the list of region/annotation to be exported is large. ([#1867](https://github.com/CARTAvis/carta-frontend/issues/1867)).
+* Fixed incorrect range values in the save image dialogue with non-convertible spectral axis images by supporting native/channel options in the spectral coordinate selector for non-convertible spectral axis images.([#2225](https://github.com/CARTAvis/carta-frontend/issues/2225)).
```
Comment (YuHsuan-Hwang) [inline CHANGELOG.md]: Use "dialog" instead of "dialogue" for consistency.

File: src/stores/FileBrowserStore/FileBrowserStore.ts [hunk 5]
```diff
@@ -80,7 +80,9 @@ export class FileBrowserStore {
     // Save image
     @observable saveFilename: string = "";
     @observable saveFileType: CARTA.FileType = CARTA.FileType.CASA;
-    @observable saveSpectralRange: string[] = ["0", "0"];
+    @observable saveSpectralStart: string;
```
Comment (YuHsuan-Hwang) [inline src/stores/FileBrowserStore/FileBrowserStore.ts]: I think it's safer to remain assigning the initial values `"0"` here.

File: src/stores/FileBrowserStore/FileBrowserStore.ts [hunk 6]
```diff
@@ -80,7 +80,9 @@ export class FileBrowserStore {
...
+    @observable saveSpectralEnd: string;
```
Comment (YuHsuan-Hwang) [inline src/stores/FileBrowserStore/FileBrowserStore.ts]: Same comment.

File: src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx [hunk 7]
```diff
@@ -174,23 +153,12 @@ export class ImageSaveComponent extends React.Component {
...
-                                            options={spectralCoordinateOptions}
-                                            onChange={(event: React.FormEvent<HTMLSelectElement>) => this.updateSpectralCoordinate(event.currentTarget.value as string)}
-                                        />
-                                        <HTMLSelect
-                                            value={activeFrame && (activeFrame.spectralSystem || "")}
-                                            options={spectralSystemOptions}
-                                            onChange={(event: React.FormEvent<HTMLSelectElement>) => this.updateSpectralSystem(event.currentTarget.value as SpectralSystem)}
-                                        />
-                                    </FormGroup>
+                                    <SpectralSettingsComponent frame={activeFrame} onSpectralCoordinateChange={this.updateSpectralCoordinate} onSpectralSystemChange={this.updateSpectralSystem} disable={false} customLabel="Range Unit" />
```
Comment (YuHsuan-Hwang) [inline src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx]: Change "Range Unit" to "Range unit" for consistency.

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx [hunk 8]
```diff
@@ -14,27 +14,32 @@ export class SpectralSettingsComponent extends React.Component<{
...
+    customLabel?: string;
 }> {
     render() {
         const frame = this.props.frame;
         const nativeSpectralCoordinate = frame?.nativeSpectralCoordinate;
         const spectralTypes = frame?.spectralCoordsSupported ? Array.from(frame.spectralCoordsSupported.keys()) : [];
         const filteredSpectralTypes = this.props.disableChannelOption ? spectralTypes.filter(type => type !== "Channel") : spectralTypes;
         const spectralCoordinateOptions: IOptionProps[] = filteredSpectralTypes.map((coord: string) => {
+            if (coord === SPECTRAL_TYPE_STRING.get(SpectralType.NATIVE)) {
+                return {value: coord, label: frame.nativeSpectralCoordinate};
```
Comment (YuHsuan-Hwang) [inline src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: I suggest we add " (Native WCS)" to the label.
`frame.nativeSpectralCoordinate` can be simplified to `nativeSpectralCoordinate`.

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx [hunk 9]
```diff
@@ -14,27 +14,32 @@ export class SpectralSettingsComponent extends React.Component<{
...
-                  return {value: system, label: system};
-              })
-            : [];
-        const hasFrameCoordinateSetting = frame && (frame.isSpectralCoordinateConvertible || (frame.spectralAxis && !frame.spectralAxis.valid));
+        const spectralSystemOptions: IOptionProps[] =
+            frame?.spectralSystemsSupported.length > 0
+                ? frame.spectralSystemsSupported.map(system => {
+                      return {value: system, label: system};
+                  })
+                : [{value: frame.spectralAxis.specsys, label: frame.spectralAxis.specsys}];
```
Comment (YuHsuan-Hwang) [inline src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: Add error handlings here: `frame?.spectralSystemsSupported?.length`, `frame.spectralAxis?.specsys`

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
The new changes look good. 👍 I have some minor comments.

File: CHANGELOG.md (hunk 4 above)
Comment (TienHao) [reply CHANGELOG.md]: has changed

File: src/stores/FileBrowserStore/FileBrowserStore.ts (hunk 5 above)
Comment (TienHao) [reply src/stores/FileBrowserStore/FileBrowserStore.ts]: modified!

File: src/stores/FileBrowserStore/FileBrowserStore.ts (hunk 6 above)
Comment (TienHao) [reply src/stores/FileBrowserStore/FileBrowserStore.ts]: as above

File: src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx (hunk 7 above)
Comment (TienHao) [reply src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx]: changed

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx (hunk 8 above)
Comment (TienHao) [reply src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: great suggestion. I have modified these

File: src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx (hunk 9 above)
Comment (TienHao) [reply src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx]: modified!

**Review by YuHsuan-Hwang — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
Requires re-testing of the feature, not only for the Save Image dialog but also for the z profiler, moment generator, PV generator, ... .

**Review by kswang1029 — APPROVED** [review]
This looks good as far as I can tell from testing 1) save image, 2) spectral profiler, 3) moment generator and 4) pv generator. No regression from e2e tests.

File: src/stores/FileBrowserStore/FileBrowserStore.ts [hunk 10]
```diff
@@ -568,12 +568,12 @@ export class FileBrowserStore {
         }
     };
 
-    @action setSaveSpectralRangeMin = (min: string) => {
-        this.saveSpectralRange[0] = min;
+    @action setSaveSpectralStart = (start: string) => {
+        this.saveSpectralStart = start;
```
Comment (crocka) [inline src/stores/FileBrowserStore/FileBrowserStore.ts:572]: can we save saveSpectralStart and saveSpectralEnd as float instead of string so we don't need to parseFloat everytime we try to use them?

Comment (TienHao) [reply src/stores/FileBrowserStore/FileBrowserStore.ts:572]: Thanks for pointing out that. I agree that setting saveSpectralStart/End as "string" is wired too. But, actually, I had changed their types back from number to string in a previous commit(d14ab2e) since the string type would cause a different checking behavior in the input fields.

> @TienHao not sure if this is due to the fix here, the input field becomes more aggressive in checking values. When it is 0 and we hit the backspace key, it stays as 0 but if when we see 0 and we enter 10, for example, it works. In other cases, if it is NaN, there is no way back. I would prefer we keep the original way for input fields. 
> 
> Screenshot 2023-09-22 at 12 32 35

I am trying whether this can be fixed by also modifying `NumericInput` to `SafeNumericInput` in the ImageSaveComponent to have a proper value checking behavior, since this is the only place left to implement `NumericInput` directly instead of `SafeNumericInput` for inputs.

**Comment by TienHao** [comment]
@kswang1029 would you help to test this PR again, especially for the value checking behavior. I found the inputs here in ImageSaveComponent were the only inputs left to use NumericInput directly, so I have changed them to SafeNumericInput. They should be like other inputs elsewhere now.

**Comment by kswang1029** [comment]
> @kswang1029 would you help to test this PR again, especially for the value checking behavior. I found the inputs here in ImageSaveComponent were the only inputs left to use NumericInput directly, so I have changed them to SafeNumericInput. They should be like other inputs elsewhere now.

Will do

**Review by kswang1029 — APPROVED** [review]

**Review by loveluthien — APPROVED** [review]
It looks good.

**Review by acdo2002 — APPROVED** [review]
I have tested the channel with supermosaic.10.fits and other images (MUSE & JWST IFU), they are all working fine.

**Review by crocka — APPROVED** [review]
