### PR TITLE
Icchen/1893 show last index of animator slider

### LINKED ISSUE #1893: Show last index of animator sliders
**Describe the bug**
After #1891, the incorrect position of the slider elements is fixed by not always showing the last index. However, it would be better if we can always show the last index on the slider to clearly show the range of the values.

**To Reproduce**
Open 13 images / open an image with 13 channels.

**Expected behavior**
Show index 13 instead of 12 or show both 13 and 12.

**Screenshots or videos**
image
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 102
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**
This PR is linked to [#1893 Show last index of animator sliders](https://github.com/CARTAvis/carta-frontend/issues/1893)
`labelValues` is adopted instead of `labelStepSize`, to force the appearance of the last index of the animator slider. The result is shown below:

image

**Checklist**
- [x] changelog updated / ~~no changelog update needed~~
- [ ] e2e test passing / added corresponding fix
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

File: src/components/Animator/AnimatorComponent.tsx [hunk 1]
```diff
@@ -235,6 +237,7 @@ export class AnimatorComponent extends React.Component<WidgetProps> {
         if (numChannels > 1) {
             const numLabels = 5;
             const channelStep = numChannels > 10 ? Math.floor((numChannels - 1) / (numLabels - 1)) : 1;
+            const tickChannels = numChannels > 10 ? [0, channelStep, 2 * channelStep, 3 * channelStep, 4 * channelStep, numChannels - 1] : Array.from(Array(numChannels).keys());
```
Comment (YuHsuan-Hwang) [inline src/components/Animator/AnimatorComponent.tsx]: with a large number of channels, the last two labels may be too close.
image

File: src/components/Animator/AnimatorComponent.tsx [hunk 2]
```diff
@@ -217,13 +217,15 @@ export class AnimatorComponent extends React.Component<WidgetProps> {
             const frameIndex = appStore.frames.findIndex(f => f.frameInfo.fileId === activeFrame.frameInfo.fileId);
             const numIndices = 5;
             const frameStep = numFrames > 10 ? Math.floor((numFrames - 1) / (numIndices - 1)) : 1;
+            const tickFrame = numFrames > 10 ? [0, frameStep, 2 * frameStep, 3 * frameStep, 4 * frameStep, numFrames - 1] : Array.from(Array(numFrames).keys());
+            console.log(frameStep);
```
Comment (YuHsuan-Hwang) [inline src/components/Animator/AnimatorComponent.tsx]: remove console.log

File: CHANGELOG.md [hunk 3]
```diff
@@ -23,6 +23,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * Fixed gaps in projected unclosed regions ([#1740](https://github.com/CARTAvis/carta-frontend/issues/1740)).
 * Fixed projection of polygon regions created on spatially matched images ([#1887](https://github.com/CARTAvis/carta-frontend/issues/1887)).
 * Fixed incorrect channels of matched images requested for animation ([#569](https://github.com/CARTAvis/carta-frontend/issues/569)).
+* Fixed issue of show last index of animator sliders ([#1893] https://github.com/CARTAvis/carta-frontend/issues/1893)
```
Comment (YuHsuan-Hwang) [inline CHANGELOG.md]: change show to showing. add `()` around the url.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

File: src/components/Animator/AnimatorComponent.tsx (hunk 1 above)
Comment (I-Chenn) [reply src/components/Animator/AnimatorComponent.tsx]: Would like to discuss a bit about this issue with @YuHsuan-Hwang  and @kswang1029.
The easiest way of solving this issue is to show only 5 ticks (instead of the current 6).
With this modification, the showing ticks are: 
0, channelStep, 2*channelStep, 3*channelStep, and numChannels - 1 (the last index).
It's the best method I can think of so far to show the necessary ticks (most importantly, the last index) and get rid of the congestion of the last two indices in most cases.
Nevertheless, it may produce wierd pattern when there are 11 or 12 elements to be shown on the slider, something like this:
image
Is it acceptable for you? I would like to take comments if you have better solutions.

Comment (YuHsuan-Hwang) [reply src/components/Animator/AnimatorComponent.tsx]: perhaps check the difference between `4 * channelStep, numChannels - 1` and remove `4 * channelStep` when needed?

Comment (I-Chenn) [reply src/components/Animator/AnimatorComponent.tsx]: Thanks for the tip.
I made some modifications following your suggestion, but adopt different methodology for frame (image) and channel, respectively. The difference is shown below:
Frame:
image
Channel
image
The reason is that we usually deal with great numbers of channel (hundreds?) while there are usually much less images (tens for most?). Although I do think that my resolution is a bit tricky and somewhat too custormized, it seems to be the best configuration so far.
Please take a look of my last commit.

Comment (YuHsuan-Hwang) [reply src/components/Animator/AnimatorComponent.tsx]: How about `numChannels - 1 - 4 * channelStep < channelStep` for both frames and channels?

Comment (I-Chenn) [reply src/components/Animator/AnimatorComponent.tsx]: Thank you! Should have thought about it.
The new commit is established.

**Comment by kswang1029** [comment]
I did a simple test by loading 21 images in CARTA and close the images one by one and observe the indices. In some cases, it appears that we can add one more index between the last two computed indices, for example, when the total number of images is 20 (I think we can put 16 between 12 and 19), or 19 (possibly to have 16 or 15 between 12 and 18), or 15 (have 12 between 9 and 14). Basically the idea is to have a tolerance (+- 1 or 2 channels) to the last step. Would this be possible?

https://user-images.githubusercontent.com/20819712/177659512-ae7c628e-57cc-4099-ab81-8bbebe89dd61.mov

**Comment by I-Chenn** [comment]
@kswang1029 Sorry for delay to reply.
I tried some modifications this morning and eventually found a tricky way of dealing with the issue, that is, to adopt "ceil" when defining frameStep and channelStep. The results are shown below:
image
image
image
I have made a new commit, please make a test again and see if it's tolerable for you.

(I think I may make a conclusion from the experience of dealing this issue: "less indices, less problem." lol)

> I did a simple test by loading 21 images in CARTA and close the images one by one and observe the indices. In some cases, it appears that we can add one more index between the last two computed indices, for example, when the total number of images is 20 (I think we can put 16 between 12 and 19), or 19 (possibly to have 16 or 15 between 12 and 18), or 15 (have 12 between 9 and 14). Basically the idea is to have a tolerance (+- 1 or 2 channels) to the last step. Would this be possible?
> 
>  Screen.Recording.2022-07-07.at.07.28.08.mov

**Comment by kswang1029** [comment]
I repeated my test with 20+ images loaded and close them one by one. Mostly it works fine. Just spotted the following two cases that I _think_ we should not show the index (9 and 12). I am open to other opinions on the logic about whether or not showing the index.

Screen Shot 2022-07-07 at 14 17 04
Screen Shot 2022-07-07 at 14 16 42

**Comment by I-Chenn** [comment]
@kswang1029 @YuHsuan-Hwang 
Sorry, I must have misunderstood Kuo-Song's last comment and didn't make further modification. I have made a new modification following Yu-Hsuan's suggestion. I have also made Kuo-Song's 21 images countdown test, and the result seems to be good for me:
image
image
Please take a glance at it.

**Comment by kswang1029** [comment]
this is more or less okay now. Could you merge dev as I see errors from e2e tests?

**Comment by kswang1029** [comment]
@I-Chenn e2e tests are not all passing. Also, it is the assignee's responsibility (in this case @YuHsuan-Hwang ) to decide if a PR can be merged or not.

**Comment by I-Chenn** [comment]
@kswang1029 OK, sorry for misunderstand that you want me to merge the branch into dev. Should I undo the merge?

**Comment by YuHsuan-Hwang** [comment]
> @kswang1029 OK, sorry for misunderstand that you want me to merge the branch into dev. Should I undo the merge?

Yes, please revert the merge

**Comment by I-Chenn** [comment]
The reverted PR is here:
https://github.com/CARTAvis/carta-frontend/pull/1913
