### PR TITLE
hips2fits UI enhancement

### LINKED ISSUE #2485: [v5-beta / HiPS2FITS] adding input upper/lower limit and tooltips
**Describe the bug**
A beta user mentioned the HiPS2FITS user interface does not provide hints on the limitation of the image size, for example. 

Here are a few things for improvements

1. "Dimension": the documentation (https://alasky.cds.unistra.fr/hips-image-services/hips2fits) says "Dimension (width x height) of the cutout can not exceed 50 million pixels.". We can add a tooltip for this.
2. "Dimension": set lower limit to a few pixels maybe? 
3. "Field of view": set upper limit to 360 deg.
4. "Rotation angle": set upper limit to 360 deg.

The user also mentioned there is no way to cancel a request. This is probably beyond our control(?).

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Sequoia
 - Browser [e.g. chrome, safari, electron app]: v5-beta electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v5-beta 
 - Frontend branch [e.g. dev, v3b2 release]: dev, v5-beta

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

Close #2485. Add a tooltip, warning, and pixel number (dimension) estimate by pixel size information.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [ ] changelog updated / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
1. Please disable cursor highlight in css. 
2. Regarding the computed pixel size, I suggest we show the value in a more friendly unit depending on the values. For example the ruler annotation can switch degrees/arcminutes/arcseconds dynamically. 

Screenshot 2025-04-22 at 13 19 23

**Review by kswang1029 — CHANGES_REQUESTED** [review]
Found that for some reason the value check does not work? 

Screenshot 2025-04-28 at 13 27 45


Please change the font to fixed-width font for the pixel size info text (to be consistent with region configuration dialog and others). And also grey it out when loading.
Screenshot 2025-04-28 at 13 31 37

File: src/stores/HipsQueryStore/HipsQueryStore.ts [hunk 1]
```diff
@@ -51,6 +51,16 @@ export enum HipsProjection {
     XPH = "XPH"
 }
 
+export enum HipsConstraint {
```
Comment (YuHsuan-Hwang) [inline src/stores/HipsQueryStore/HipsQueryStore.ts]: I think it is uncommon to assign the same values in an enum which could cause problems when comparing values. We could use an object instead since it's unnecessary to use an enum here.

File: src/stores/HipsQueryStore/HipsQueryStore.ts [hunk 2]
```diff
@@ -78,7 +88,24 @@ export class HipsQueryStore {
 
     /** Whether the current state is valid for a HiPS data query. */
     @computed get isValid(): boolean {
-        return this.hipsSurvey.length > 0 && this.size.x > 0 && this.size.y > 0 && (this.object.length > 0 || (isFinite(this.center.x) && isFinite(this.center.y))) && this.fov > 0 && isFinite(this.rotationAngle) && !this.isLoading;
+        return this.hipsSurvey.length > 0 && this.isDemValid && (this.object.length > 0 || (isFinite(this.center.x) && isFinite(this.center.y))) && this.isFovValid && this.isRotAngleValid && !this.isLoading;
+    }
+
+    @computed get isDemValid(): boolean {
```
Comment (YuHsuan-Hwang) [inline src/stores/HipsQueryStore/HipsQueryStore.ts]: I prefer we use `Dimension` or `Size` without abbreviation.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

**Review by kswang1029 — APPROVED** [review]
looks good. passing e2e.

File: src/stores/HipsQueryStore/HipsQueryStore.ts [hunk 3]
```diff
@@ -113,6 +130,15 @@ export class HipsQueryStore {
         [HipsProjection.XPH, "HEALPix polar, aka “butterfly”"]
     ]);
 
+    readonly HipsConstraint = {
+        MinDems: 5,
+        MaxDems: 5e7,
```
Comment (YuHsuan-Hwang) [inline src/stores/HipsQueryStore/HipsQueryStore.ts]: I prefer we use `Dimension`.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

File: src/stores/HipsQueryStore/HipsQueryStore.ts (hunk 3 above)
Comment (loveluthien) [reply src/stores/HipsQueryStore/HipsQueryStore.ts]: sorry, my bad.

**Review by YuHsuan-Hwang — APPROVED** [review]
Good work. 👍
