### PR TITLE
Jason/issue 1277

### LINKED ISSUE #1277: fail to resume a session when in-memory moment images exist
Reproduce: 
Open a cube image and request some moment images. Disconnect the back-end and reconnect it. The front-end will ask user whether to resume, but it will be failed on both server or desktop carta.

Testing:
The resume functionality is good while we have several images which is load from file.

### PR DESCRIPTION
**Pull request by duidae**
closes #1277

please also help check whether the warning wordings are appropriate, thanks.

image

### CODE REVIEW

File: src/stores/AppStore.ts [hunk 1]
```diff
@@ -1361,7 +1361,7 @@ export class AppStore {
     };
 
     handleReconnectStream = () => {
-        this.alertStore.showInteractiveAlert("You have reconnected to the CARTA server. Do you want to resume your session?", this.onResumeAlertClosed);
+        this.alertStore.showInteractiveAlert("You have reconnected to the CARTA server. Do you want to resume your session(moment map images will be ignored)?", this.onResumeAlertClosed);
```
Comment (veggiesaurus) [inline src/stores/AppStore.ts]: What about this?

> Do you want to resume your session? Please note that temporary images such as moment maps will be unloaded.

Summoning @confluence and @kswang1029 for wording checks

**Comment by kswang1029** [comment]
how about: 
> Do you want to resume your session? Please note that temporary images such as moment images or PV images generated via the GUI will be unloaded.

**Review by veggiesaurus — APPROVED** [review]
