### PR TITLE
 Fixed #483 : reopen file browser

### LINKED ISSUE #483: hanging file list if we open image file browser without closing region file browser and vice versa
To reproduce the issue, open image file browser, then open region file browser without closing the image file browser dialog. 

Or, open region file browser, then open image file browser without closing the region file browser dialog.

### PR DESCRIPTION
**Pull request by zarda**
Move back getFileList() and only reload file list after opening file browser.

### CODE REVIEW

File: src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx [hunk 1]
```diff
@@ -195,7 +195,7 @@ export class FileBrowserDialogComponent extends React.Component<{ appStore: AppS
             lazy: true,
             isOpen: fileBrowserStore.fileBrowserDialogVisible,
             onClose: fileBrowserStore.hideFileBrowser,
-            onOpened: () => fileBrowserStore.getFileList(fileBrowserStore.startingDirectory),
+            onOpened: () => {const _list = fileBrowserStore.fileList; fileBrowserStore.fileList = null; fileBrowserStore.fileList = _list; },
```
Comment (veggiesaurus) [inline src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx]: this should be a private class function instead of an anonymous function. The frontend also doesn't use `_` for any varible names, so rather avoid that and use a descriptive name for it. Maybe `tempList`?

This all looks a bit hacky. `fileBrowserStore.fileList` is an observable, I'd rather we edited it throuh an `@action`

Comment (zarda) [reply src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx]: Fixed it. I will looking into a better solution behind blueprint.
