### PR TITLE
Jason/fix 73

### LINKED ISSUE #73: [imageViewer, AST] incorrect native coordinate when reopening an image
frontend version: f6daeb9, tested with MBP

to reproduce this issue:
1) open J2000_test.hdf5
2) change the coordinate system from "native" to "galactic"
3) reopen J2000_test.hdf5 (not append image)
4) now the coordinate system of the grid line is still "galactic" which may be okay (ideally maybe we should reset it to "native")
4) change the coordinate system from "galactic" to "native" (should be FK5) and we see
screen shot 2018-10-25 at 12 51 56
The system seems still galactic but its label format changes to FK5.

### PR DESCRIPTION
**Pull request by duidae**
we use implicit system(parameter system="") in overlay store in order to provide native option for users,  however current logic will not append "system" parameter when its value is an empty string, then the AST just use previous coordinate system to render. The solution is to set explicit system (saved in defaultSystem) to AST.

closes #73

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@confluence, since you wrote most of this stuff, can you give it a check?

File: src/components/ImageView/Overlay/OverlayComponent.tsx [hunk 1]
```diff
@@ -72,10 +72,6 @@ export class OverlayComponent extends React.Component<OverlayComponentProps> {
 
     render() {
         const styleString = this.props.overlaySettings.styleString;
-        const frameView = this.props.frame.requiredFrameView;
```
Comment (veggiesaurus) [inline src/components/ImageView/Overlay/OverlayComponent.tsx]: I think those are in there to ensure that changing the frame view, padding or width/height triggers a re-render

Comment (duidae) [reply src/components/ImageView/Overlay/OverlayComponent.tsx]: oh! sorry about that, I'll restore those codes
