### PR TITLE
fix multi-spectral profile colors for images

### LINKED ISSUE #2236: profile colors are changed with active image in the multi-profile plot mode for "image"
**Describe the bug**
(reported as a usability problem from a user)

If we have cubes matched and enable multi-profile plot mode in the spectral profiler, when we change the active image we will see profile colors are changed too. This would make users hard to identify which profile refers to which image.

**To Reproduce**
1. load multiple cubes and match them spatially and spectrally
2. enable spectral profiler and enable multi-profile mode for "image"
3. observe the colors in the spectral profiler
4. change active image and re-observe the colors in the spectral profiler. We should see for a given profile the color is changed.

**Expected behavior**
In the multi-profile mode for "image", for a given image the profile color should stay the same regardless which image is active.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 106
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

This PR closes #2236. The colors of spectral profiles in multi-image mode are fixed, i.e., the color doesn't vary with activeFrame changes. Adding support for plotting the selected frames. The multi-region, statistic, and polarization profiles adopt the same color assigning method.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
In this test case we have three cubes matched spatially and spectrally. Then we enable multiple-profile mode for images and select all images in the image dropdown menu to see three profiles. Now if we unmatch spatially or spectrally using the active image, we will see the profile plot becomes inconsistent. I suggest when this happens, we should de-select the image in the image dropdown list so that we can still see two profiles from matched cubes.


https://github.com/user-attachments/assets/3fde4deb-24dd-4efb-adae-7b4ee77f4fd5

File: src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts [hunk 1]
```diff
@@ -688,18 +737,10 @@ export class SpectralProfileSelectionStore {
             }
         });
 
-        // When in Multi profile mode of Image and there are matched files(may change dynamically), assign them colors
+        // Selecting active frame in the single frame mode
         autorun(() => {
-            const matchedFileIds = AppStore.Instance.spatialAndSpectalMatchedFileIds;
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts:693]: Looks like implementation in `autorun` need to be preserved.

**Review by YuHsuan-Hwang — APPROVED** [review]
The new approach looks good. 👍

**Review by kswang1029 — APPROVED** [review]
looks good. Two e2e tests are revised accordingly.

File: src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts [hunk 2]
```diff
@@ -688,19 +738,35 @@ export class SpectralProfileSelectionStore {
...
+
+        reaction(
+            () => {
+                const matchedFileIds = AppStore.Instance.spatialAndSpectalMatchedFileIds;
+                return matchedFileIds;
+            },
+            matchedFileIds => {
+                if (this.activeProfileCategory === MultiProfileCategory.IMAGE) {
+                    // remove the profile if it is unmatched
+                    if (this.selectedFileIds.length > 0) {
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts]: Checking the length is unnecessary for `forEach`.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
Minor comment.

File: src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts (hunk 2 above)
Comment (loveluthien) [reply src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts]: Fixed

**Review by YuHsuan-Hwang — APPROVED** [review]
