### PR TITLE
Use spherical geometry for offset coordinate system instead of linear geometry

### LINKED ISSUE #2662: including Dec in scaling RA offset coordinate
The RA offset coordinate calculation needs to consider the reference Dec value in order to get the right offset values.

The following screenshot shows a "circular" gaussian at high latitude and due to SIN projection scheme, it is distorted. The RA offset (incorrect) and Dec offset (correct) are not consistently reflecting a circular gaussian. 

Image

**To Reproduce**
1. better use a synthetic circular gaussian image for debugging, put the source at high latitude 
2. switch to offset coordinate grid and check the tick values in RA and Dec to see inconsistencies 

**Expected behavior**
Offset RA and Dec scale independent of target Dec value 

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Sequoia
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v5.1
 - Frontend branch [e.g. dev, v3b2 release]: dev, v5.1

### PR DESCRIPTION
**Pull request by izkgao**
**Description**

Closes #2662.

This PR updates the offset coordinate system implementation in the AST wrapper to use proper spherical geometry instead of linear geometry for astronomical coordinate transformations and renames "shifted" to "offset".

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

### CODE REVIEW

File: wasm_src/ast_wrapper/ast_wrapper.cc [hunk 1]
```diff
@@ -204,26 +204,34 @@ EMSCRIPTEN_KEEPALIVE AstFrameSet* createTransformedFrameset(AstFrameSet* wcsinfo
...
-    // remapping
-    astRemapFrame(wcsinfoShifted, 2, shiftMap);
-
-    AstSkyFrame *skyframe = static_cast<AstSkyFrame*>astGetFrame(wcsinfoShifted, 2);
-    astSet(skyframe, "SkyRefIs=Origin");
-
-    // 2D pixel shifts
+EMSCRIPTEN_KEEPALIVE AstFrameSet* createOffsetFrameset(AstFrameSet* wcsinfo, double offsetX, double offsetY, double pixelOffsetX, double pixelOffsetY)
+{
+    AstFrameSet* wcsinfoOffset = static_cast<AstFrameSet*> astCopy(wcsinfo);
```
Comment (loveluthien) [inline wasm_src/ast_wrapper/ast_wrapper.cc]: wcsinfoOffset -> wcsInfoOffset
wcsinfo -> wcsInfo

**Review by loveluthien — APPROVED** [review]
😎

**Review by kswang1029 — APPROVED** [review]
