### PR TITLE
fix no wcs grid if filename contains comma character

### LINKED ISSUE #2386: no wcs grid for DES fits image
**Describe the bug**
This is a user bug report. If we load the image

https://drive.google.com/file/d/1bDbI9-DV-nAssT5bJslAvMOdHWaO7qhJ/view?usp=drive_web

we do not see the wcs grid rendered properly. The console shows errors as

Screenshot 2024-06-01 at 18 24 06

line277:     `plot = astPlot(wcsinfo, gbox, pbox, args);`

If we load the image in ds9 and save as a slice in fits again, then the wcs grid can be rendered successfully in CARTA. For some reason, this trick regulates the fits header.

Let's see if a fix can be applied to handle this case (or not, ie headers fault)

**To Reproduce**
1. download the example image https://drive.google.com/file/d/1bDbI9-DV-nAssT5bJslAvMOdHWaO7qhJ/view?usp=drive_web
2. load it in CARTA and we won't see wcs grid rendered properly.
3. load the image in ds9 and save as a slice
4. load the ds9-processed fits image in CARTA and we will see the wcs grid rendered properly.

**Expected behavior**
can handle such fits header

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS ventura
 - Browser [e.g. chrome, safari, electron app]: electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v4.1-stable
 - Frontend branch [e.g. dev, v3b2 release]: v4.1-stable

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

Closed #2386. Filename includes comma characters that cause a failure to draw a coordinate system. Since AST uses commas to separate the list and read the attributes, filenames with commas make an AST unrecognized keyword and fail to plot the WCS overlay. 

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~/ no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

File: src/components/ImageView/Overlay/OverlayComponent.tsx [hunk 1]
```diff
@@ -150,7 +150,7 @@ export class OverlayComponent extends React.Component<OverlayComponentProps> {
             }
 
             if (!settings.title.customText) {
-                currentStyleString += `, Title=${this.props.image?.store?.filename}`;
+                currentStyleString += `, Title=${this.props.image?.store?.filename.replaceAll(",", "_")}`;
```
Comment (kswang1029) [inline src/components/ImageView/Overlay/OverlayComponent.tsx]: it seems % also causes the issue. We can use the image viewer settings - title to have a custom text for experimentation. If , or % is in the string, the WCS layout is gone. Interestingly, if , is the late char, it survives but it is not rendered.

File: wasm_src/ast_wrapper/ast_wrapper.cc [hunk 2]
```diff
@@ -260,23 +260,6 @@ EMSCRIPTEN_KEEPALIVE int plotGrid(AstFrameSet* wcsinfo, double imageX1, double i
     double pbox[] = {imageX1, imageY1, imageX2, imageY2};
     plot = astPlot(wcsinfo, gbox, pbox, args);
 
-    // add RA/Dec reference
-    if (strlen(system) > 0)
-    {
-        const char* symbol1 = astGetC(plot, "Symbol(1)");
-        if (strcmp(symbol1, "RA") == 0 || strcmp(symbol1, "Dec") == 0)
```
Comment (YuHsuan-Hwang) [inline wasm_src/ast_wrapper/ast_wrapper.cc:268]: We check for "RA" and "Dec" when adding the reference. Please add the same logic in `OverlayStore`.

File: src/stores/OverlayStore/OverlayStore.ts [hunk 3]
```diff
@@ -100,11 +100,18 @@ export class OverlayGlobalSettings {
...
+
         const isWcsFrameAndSystem = typeof this.explicitSystem !== "undefined" && this.explicitSystem !== SystemType.Image && frame.validWcs;
         if (isWcsFrameAndSystem) {
             astString.add("System", this.explicitSystem);
         }
 
+        const labelX = AST.getString(frame?.wcsInfo, "Label(1)");
+        const labelY = AST.getString(frame?.wcsInfo, "Label(2)");
+        const system = typeof this.explicitSystem !== "undefined" ? this.explicitSystem : "pixel";
+        astString.add("Label(1)", `"${labelX.replace(/%/g, "%%%%")} (${system})"`, labelX !== undefined);
```
Comment (YuHsuan-Hwang) [inline src/stores/OverlayStore/OverlayStore.ts]: Perhaps we could avoid adding two `"Label(1)"` when custom text is enabled.

File: src/stores/OverlayStore/OverlayStore.ts [hunk 4]
```diff
@@ -100,11 +100,18 @@ export class OverlayGlobalSettings {
...
+        astString.add("Label(2)", `"${labelX.replace(/%/g, "%%%%")} (${system})"`, labelY !== undefined);
```
Comment (YuHsuan-Hwang) [inline src/stores/OverlayStore/OverlayStore.ts]: Typo: `labelY`.

File: wasm_src/ast_wrapper/ast_wrapper.cc [hunk 5]
```diff
@@ -51,7 +51,7 @@ EMSCRIPTEN_KEEPALIVE AstFrameSet* getFrameFromFitsChan(AstFitsChan* fitschan, bo
     }
 
     AstFrame* pixFrame = static_cast<AstFrame*> astGetFrame(frameSet, 1);
-    astSet(pixFrame, "Label(1)=X coordinate (pixel),Label(2)=Y coordinate (pixel)");
+    astSet(pixFrame, "Label(1)=X coordinate,Label(2)=Y coordinate");
```
Comment (YuHsuan-Hwang) [inline wasm_src/ast_wrapper/ast_wrapper.cc:55]: The label is changed from `X coordinate (pixel)` to `X coordinate (CARTESIAN)` for image coordinates. Wonder if we should remain the same behavior.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

File: wasm_src/ast_wrapper/ast_wrapper.cc (hunk 5 above)
Comment (loveluthien) [reply wasm_src/ast_wrapper/ast_wrapper.cc:55]: fix it

**Review by kswang1029 — CHANGES_REQUESTED** [review]
found an issue with the current solution: if we enter `",`, AST layout will be gone. Guess we need also a special handle for this case....

The layout will be gone when `,` presents after `"` (not necessary right after), for example, `ABC"DEF,` will also trigger the issue.

Screenshot 2025-04-22 at 13 57 33

File: src/stores/OverlayStore/OverlayStore.ts [hunk 6]
```diff
@@ -100,11 +100,23 @@ export class OverlayGlobalSettings {
...
         astString.add("Color", AstColorsIndex.GLOBAL);
         astString.add("Tol", toFixed(this.tolerance / 100, 2), this.tolerance >= 0.001); // convert to fraction
+
         const isWcsFrameAndSystem = typeof this.explicitSystem !== "undefined" && this.explicitSystem !== SystemType.Image && frame.validWcs;
         if (isWcsFrameAndSystem) {
             astString.add("System", this.explicitSystem);
         }
 
+        if (!AppStore.Instance?.overlayStore?.labels?.customText) {
+            const symbol1 = AST.getString(frame?.wcsInfo, "Symbol(1)");
```
Comment (YuHsuan-Hwang) [inline src/stores/OverlayStore/OverlayStore.ts]: Please check for the two axis and add the reference separately. This is for handling spatial-spectral images, for example:
image
The ` (FK5)` in y axis needs to be removed.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
Looks like we also get incorrect labels when the custom text is set to `"`:
image
Note: we get the same behavior in v5-beta. We can consider creating a new issue if it's not straightforward to fix it.

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good. 👍

**Review by kswang1029 — APPROVED** [review]
looking good.

**Review by YuHsuan-Hwang — APPROVED** [review]
