### PR TITLE
fix zero reference line in the scatter plot

### LINKED ISSUE #2531: bold 0, 0 axes in stokes Widget
For the Q versus U plot in the Stokes widget it would be good to plot the  axes y=0 and x =0 as bold.  One of the things the user wants to access by looking at the scatter  plot is that the centroid is offset from (0,0).  This is difficult to visualise in the current implementation. If the origin axes were in bold, it would be very helpful.

### LINKED ISSUE #2532: incorrect zero axes props in the QU scatter plot of the Stokes analysis widget
**Describe the bug**
The zero axes are highlighted incorrectly as demonstrated in the video (note the color and thickness are enhanced in order to see the issue easily).

https://github.com/user-attachments/assets/e58d72e4-3130-4aa5-8fc2-764463657cc1

**To Reproduce**
1. load a Stokes cube and enable the Stokes analysis widget
2. observe the zero axes color and width and pay attention to think grid lines which should not be the case
3. zoom the scatter plot and observe
4. in the settings dialog, enable/disable the equal axes toggle and observe

**Expected behavior**
The zero axes should be highlighted correctly (see #2531 as well).

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Sequoia
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v5-beta
 - Frontend branch [e.g. dev, v3b2 release]: dev, v5-beta

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

Close #2531 and close #2532. The zero-reference axis lines did not align at (0, 0). Now they are pointing to the tick value 0. Adding a switcher for plotting the zero-reference axis lines in the setting of the Stokes analysis widget.

**Checklist**

- zero-reference axis lines at (0,0)
- line color and thickness

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] protobuf version bumped / ~no protobuf version bumped needed~
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [x] corresponding ICD test fix added (`BackendService` changed) / ~no ICD test fix needed (`BackendService` unchanged)~
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

File: src/stores/Widgets/StokesAnalysisWidgetStore/StokesAnalysisWidgetStore.ts [hunk 1]
```diff
@@ -72,6 +73,9 @@ export class StokesAnalysisWidgetStore extends RegionWidgetStore {
     @observable colorPixel: {color: Uint8ClampedArray; size: number};
     @observable pointTransparency: number;
     @observable invertedColorMap: boolean;
+    @observable showReferenceAxes: boolean;
+    @observable referenceAxesThickness: number;
+    @observable referenceAxesColor: string;
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/StokesAnalysisWidgetStore/StokesAnalysisWidgetStore.ts]: Perhaps it's not necessary to set `referenceAxesThickness` and `referenceAxesColor` as observables if they are never changed.

File: src/stores/Widgets/StokesAnalysisWidgetStore/StokesAnalysisWidgetStore.ts [hunk 2]
```diff
@@ -234,6 +238,9 @@ export class StokesAnalysisWidgetStore extends RegionWidgetStore {
         this.smoothingStore = new ProfileSmoothingStore();
         this.settingsTabId = StokesAnalysisSettingsTabs.CONVERSION;
         this.invertedColorMap = DEFAULTS.invertedColorMap;
+        this.showReferenceAxes = false;
+        this.referenceAxesThickness = 2;
+        this.referenceAxesColor = AppStore.Instance.darkTheme ? Colors.LIGHT_GRAY3 : Colors.GRAY3;
```
Comment (YuHsuan-Hwang) [inline src/stores/Widgets/StokesAnalysisWidgetStore/StokesAnalysisWidgetStore.ts]: We might need the color to be responsive to the theme. The line remains light gray when we open the widget and change the theme from dark to light.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
The bug fix looks good. Some comments for the new style config.

**Review by kswang1029 — APPROVED** [review]
this looks fine. Please set the "Reference axes" toggle on as default. In the dark mode, maybe having a slightly dimmer axes (now it is a bit bright in my point of view) would be better to view. 


note that the "equal axes" seems not working properly in the rendered result. We should visit this in a separate PR.

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good. 👍
