### PR TITLE
carli/1950_1951_1952_pv_x_y_axis_setting

### LINKED ISSUE #1950: PV generator: support spatial as x and spectral as y AND spatial as y and spectral as x (frontend)
user feedback from v3 beta test

This is an enhancement that users can configure the axes order of the resulting pv image from the pv generator. With v3 release, the offset axis is in x and the spectral axis is in y. We need to provide an option to generate a pv image with the offset axis in y and the spectral axis in x.

This requires protobuf message update.

The companion backend issue is https://github.com/CARTAvis/carta-backend/issues/1175

### LINKED ISSUE #1951: Having an option to keep or replace generated moment or pv images when a new request is made (frontend)
user feedback from v3 beta test

With v3 release, when a new request made in the pv generator or moment generator, generated images from the previous request will be removed. Users would like to have an option to keep or replace the pv or moment images. 

The companion backend issue is https://github.com/CARTAvis/carta-backend/issues/1176

### LINKED ISSUE #1952: Set a range to the spectral axis to generate a pv image (frontend)
user feedback from v3 beta test

With v3 release, a PV image is generated using the entire spectral axis along the pv cut. The enhancement is to be able to set a spectral range to generate a pv image. This is helpful to focus on a certain line feature in the cube.

The companion backend feature is https://github.com/CARTAvis/carta-backend/issues/1177

### LINKED ISSUE #2020: Moment generator range input fields' default values do not update with coordinate change
**Describe the bug**
The range input field's default value do not change when coordinate system changes.

**To Reproduce**
1. Go to 'Moment Generator'
2. Click on 'Coordinate' and select a different coordinate.
3. See that the number in the range input fields do not change.

**Expected behavior**
Expect to see the range input default values change to the selected coordinate system.

### PR DESCRIPTION
**Pull request by crocka**
**Description**
This is enhancement feature 1950, 1951, and 1952. In the PV generator widget, we added a selection option in the PV generator widget to swap x and y axis, an input for spectral axis limit, and a toggle button to let users decide whether or not to keep the previously generated PV images.

This pr alse resolved #2020 

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] ~e2e test passing~ / added corresponding fix
- [x] changelog updated / ~~no changelog update needed~~
- [x] protobuf updated to the latest dev commit / ~~no protobuf update needed~~
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

File: src/components/PvGenerator/PvGeneratorComponent.tsx [hunk 1]
```diff
@@ -216,6 +302,17 @@ export class PvGeneratorComponent extends React.Component<WidgetProps> {
                     </Tabs>
                 </div>
                 <ReactResizeDetector handleWidth handleHeight onResize={this.onResize} refreshMode={"throttle"} refreshRate={33}></ReactResizeDetector>
+                <ConfirmationDialogComponent
```
Comment (YuHsuan-Hwang) [inline src/components/PvGenerator/PvGeneratorComponent.tsx]: Maybe it's simpler to use `<Alert>` here (with Yes/No buttons and Cancel by clicking elsewhere). I'm wondering if it's more clear to set a "overwrite generated PV images" toggle in the settings?

File: src/stores/widgets/PvGeneratorWidgetStore.ts [hunk 2]
```diff
@@ -3,9 +3,18 @@ import {IOptionProps} from "@blueprintjs/core";
...
+export enum PVAxis {
+    SPATIAL = "Spatial",
+    SPECTRAL = "Spectral"
+}
 
 export class PvGeneratorWidgetStore extends RegionWidgetStore {
     @observable width: number;
+    @observable reverse: boolean;
+    @observable keep: boolean;
+    @observable range: CARTA.IIntBounds = {min: null, max: null};
```
Comment (YuHsuan-Hwang) [inline src/stores/widgets/PvGeneratorWidgetStore.ts]: image
I think it would be useful if we set the entire spectral range as default, like in the moment generator.

File: src/components/PvGenerator/PvGeneratorComponent.tsx [hunk 3]
```diff
@@ -19,6 +19,9 @@ export enum PvGeneratorComponentTabs {
 @observer
 export class PvGeneratorComponent extends React.Component<WidgetProps> {
     @observable selectedTabId: TabId = PvGeneratorComponentTabs.PV_IMAGE;
+    axesOrder = {};
+    @observable isConfirmationDialogOpen: boolean = false;
+    @observable error: boolean = false;
```
Comment (YuHsuan-Hwang) [inline src/components/PvGenerator/PvGeneratorComponent.tsx]: perhaps rename to `isValidSpectralRange`

**Review by YuHsuan-Hwang — COMMENTED** [review]
The features are looking nice. Some initial comments:

File: src/stores/widgets/PvGeneratorWidgetStore.ts (hunk 2 above)
Comment (crocka) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: I realized that the moment generator range input isn't updating when we change the coordinate. I fixed it but I will reverse it if it is not a desirable behaviour.

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 3 above)
Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: Updated

File: src/stores/widgets/PvGeneratorWidgetStore.ts (hunk 2 above)
Comment (crocka) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: The input fields now should display the entire spectral range in selected coordinate as default.

**Comment by kswang1029** [comment]
The generate button is disabled in the following example while a spectral range is configured. Once it is disabled, it seems there is no way back.

https://user-images.githubusercontent.com/20819712/190533829-86d737d6-9aa6-4a43-ba9e-0a3ca3c91ad4.mov

**Comment by kswang1029** [comment]
When the coordinate is velocity, it seems the range is not set correctly in the protobuf message resulting an incorrect pv image returned. 

Screen Shot 2022-09-16 at 09 08 20

oh, the issue is if we _switch_ to another coordinate convention and trigger the pv generation, the spectral range is not configured properly in the protobuf message. So it is not specific to velocity.

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 1 above)
Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: Maybe we can keep all the pv images by default and we can have a button in the pv generator that clear all the existing pv images without generating new images and when users click on clear all pv images, we alert the users "do you want to clear all the pv images?"

File: src/stores/widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts [hunk 4]
```diff
@@ -334,6 +334,15 @@ export class SpectralProfileWidgetStore extends RegionWidgetStore {
             }
         );
 
+        reaction(
```
Comment (crocka) [inline src/stores/widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts:351]: I realized in the moment generator that when we change the coordinate system, the values on the textbox do not update automatically so I added this fix.

**Comment by crocka** [comment]
> When the coordinate is velocity, it seems the range is not set correctly in the protobuf message resulting an incorrect pv image returned.
> 
> Screen Shot 2022-09-16 at 09 08 20
> 
> oh, the issue is if we _switch_ to another coordinate convention and trigger the pv generation, the spectral range is not configured properly in the protobuf message. So it is not specific to velocity.

These two issues are related to spectralTransform method in ast_wrapper that is used to transform different units into channel number. When we switch any coordinates other than frequecy (GHz, Hz, etc), the minimum limit would produce the largest channel, so in the case for the file you opened in the video, the lower limit of radio velocity is ~-45 and the upper limit is ~33, and the channel ranges from 0 - 249. The spectralTransform method transforms -45 to 249 and 33 to 0. I am not sure if this behaviour is intended but it is also what happens in moment generator, though the moment generator swapped the spectral range before sending it to the backend so it doesn't cause any error. I have implemented something similar in pv generator for now. Please let me know if this is not an intended behaviour.

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 1 above)
Comment (kswang1029) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: Usually we try different pv cuts and explore the results iteratively. That's why we need the ability to keep or remove the generated pv images. The current "alert" with yes/no is a bit interruptive as every time we will be asked once again. I would suggest either we use a toggle or a button in the main widget for keeping or removing existing pv images. As for a toggle or a button, I don't have a preference. 🤔

Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: I have added a toggle button. Please review.

**Comment by kswang1029** [comment]
@crocka could you put the toggle to the last? Also the "gap" between Range and Axes order seems a bit larger than others.
Screen Shot 2022-09-20 at 10 30 52

**Comment by kswang1029** [comment]
@crocka good for PR. 👍

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 3 above)
Comment (YuHsuan-Hwang) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: Sorry, looks like the meaning is opposite now. perhaps rename to `inValidSpectralRange`

Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: I think inValidSpectralRange would mean the same thing as isValidSpectralRange. I might as well change the logic that uses isValidSpectralRange and keep the name?

Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: Thank you for pointing that out.

File: src/components/PvGenerator/PvGeneratorComponent.tsx [hunk 5]
```diff
@@ -134,25 +140,75 @@ export class PvGeneratorComponent extends React.Component<WidgetProps> {
...
+        }
+    };
+
     render() {
         const appStore = AppStore.Instance;
         const frame = this.widgetStore.effectiveFrame;
         const fileInfo = frame ? `${appStore.getFrameIndex(frame.frameInfo.fileId)}: ${frame.filename}` : undefined;
         const regionInfo = this.widgetStore.effectiveRegionInfo;
 
+        this.genAxisOptions();
```
Comment (YuHsuan-Hwang) [inline src/components/PvGenerator/PvGeneratorComponent.tsx]: Could we call this function once in the constructor so we don't need to recalculate in rendering?

File: src/components/PvGenerator/PvGeneratorComponent.tsx [hunk 6]
```diff
@@ -134,25 +140,75 @@ export class PvGeneratorComponent extends React.Component<WidgetProps> {
...
+        let channelIndexMin = frame.findChannelIndexByValue(this.widgetStore.range?.min);
+        let channelIndexMax = frame.findChannelIndexByValue(this.widgetStore.range?.max);
+
+        if (channelIndexMin > channelIndexMax) {
+            const holder = channelIndexMax;
+            channelIndexMax = channelIndexMin;
+            channelIndexMin = holder;
+        }
+
+        if ((channelIndexMin < channelIndexMax && channelIndexMax < frame.numChannels) || (!this.widgetStore.range?.min && !this.widgetStore.range?.max && this.widgetStore.range?.min && this.widgetStore.range?.max)) {
```
Comment (YuHsuan-Hwang) [inline src/components/PvGenerator/PvGeneratorComponent.tsx]: Shall we check `isFinite(this.widgetStore.range?.min) && isFinite(this.widgetStore.range?.max)`?

File: src/stores/widgets/PvGeneratorWidgetStore.ts [hunk 7]
```diff
@@ -28,15 +37,32 @@ export class PvGeneratorWidgetStore extends RegionWidgetStore {
...
+            }
+            channelIndexMin = channelIndexMax - 1;
+        }
         if (frame && this.effectiveRegion) {
             const requestMessage: CARTA.IPvRequest = {
                 fileId: frame.frameInfo.fileId,
                 regionId: this.effectiveRegionId,
-                width: this.width
+                width: this.width,
+                spectralRange: !channelIndexMin && !channelIndexMax && channelIndexMin !== 0 && channelIndexMax !== 0 ? null : {min: channelIndexMin, max: channelIndexMax},
```
Comment (YuHsuan-Hwang) [inline src/stores/widgets/PvGeneratorWidgetStore.ts]: Shall we check `!isFinite(channelIndexMin) || !isFinite(channelIndexMax)`?

File: src/stores/widgets/PvGeneratorWidgetStore.ts [hunk 8]
```diff
@@ -48,13 +74,48 @@ export class PvGeneratorWidgetStore extends RegionWidgetStore {
...
+        if (isFinite(range.min) && isFinite(range.max)) {
+            this.range = range;
+        }
+    };
+
     constructor() {
         super(RegionsType.LINE);
         makeObservable(this);
         this.width = 3;
+        this.reverse = false;
```
Comment (YuHsuan-Hwang) [inline src/stores/widgets/PvGeneratorWidgetStore.ts:111]: We may also initialize `this.keep` here

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

File: src/stores/widgets/PvGeneratorWidgetStore.ts (hunk 7 above)
Comment (crocka) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: shouldn't we check for isFinite(channelIndexMin) && isFinite(channelIndexMax)?

**Comment by kswang1029** [comment]
no regression is observed from the current e2e tests. Due to UI changes, I have created a fix branch and it will be merged after the pair of PV improvements is merged.

After some code review, I will re-run e2e tests.

File: src/stores/widgets/PvGeneratorWidgetStore.ts (hunk 8 above)
Comment (crocka) [reply src/stores/widgets/PvGeneratorWidgetStore.ts:111]: resolved

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 6 above)
Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: resolved

File: src/components/PvGenerator/PvGeneratorComponent.tsx (hunk 5 above)
Comment (crocka) [reply src/components/PvGenerator/PvGeneratorComponent.tsx]: resolved

File: src/stores/widgets/PvGeneratorWidgetStore.ts (hunk 7 above)
Comment (YuHsuan-Hwang) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: both ok, depending on the position of `null`?

Comment (YuHsuan-Hwang) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: @crocka shall we have `isFinite(channelIndexMin) && isFinite(channelIndexMax) ? {min: channelIndexMin, max: channelIndexMax} : null`?

Comment (crocka) [reply src/stores/widgets/PvGeneratorWidgetStore.ts]: Yes, I am sorry for the mistake.

**Review by kswang1029 — APPROVED** [review]
manual tests look good. fix for e2e test is made and no regression is observed. 👍 please proceed code review.

File: src/stores/AppStore.ts [hunk 9]
```diff
@@ -478,6 +478,7 @@ export class AppStore {
             this.frames[existingFrameIndex].clearContours(false);
             this.frames[existingFrameIndex] = newFrame;
         } else {
+            // if(ack.fileId === 1000) newFrame.frameInfo.fileId = 1000 + this.frames[0]?.pvImages.length;
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore.ts]: remove comment

File: src/stores/Frame/FrameStore.ts [hunk 10]
```diff
@@ -563,7 +563,22 @@ export class FrameStore {
...
+        }
+        return false;
+    }
+
+    @computed get isReversedPVImage(): boolean {
+        if (this.isPVImage) {
+            const entries = this.frameInfo.fileInfoExtended.headerEntries;
+            const axis1 = entries.find(entry => entry.name.includes("CTYPE1"));
+            const axis2 = entries.find(entry => entry.name.includes("CTYPE2"));
+            // const axis1SpectralAxis2Spatial = axis1?.value?.match(/offset|position|offset position/i) && axis2?.value?.match(/freq/i);
```
Comment (YuHsuan-Hwang) [inline src/stores/Frame/FrameStore.ts]: remove comment

**Review by YuHsuan-Hwang — APPROVED** [review]

File: src/stores/AppStore.ts [hunk 11]
```diff
@@ -1059,17 +1060,19 @@ export class AppStore {
...
+    @flow.bound *requestPV(message: CARTA.IPvRequest, frame: FrameStore, keep: boolean) {
         if (!message || !frame) {
             return;
         }
 
         this.startFileLoading();
         // clear previously generated moment images under this frame
-        if (frame.pvImage) {
-            this.closeFile(frame.pvImage);
+        if (!keep) {
```
Comment (veggiesaurus) [inline src/stores/AppStore.ts]: can we change this to `keepExisting`?

**Review by veggiesaurus — DISMISSED** [review]
just one minor change, plus @YuHsuan-Hwang's suggested changes

**Comment by kswang1029** [comment]
retested and all are good.

File: src/components/PvGenerator/PvGeneratorComponent.tsx [hunk 12]
```diff
@@ -200,6 +254,42 @@ export class PvGeneratorComponent extends React.Component<WidgetProps> {
...
+                )}
+                <FormGroup className="label-info-group" inline={true} label="Axes Order">
+                    <HTMLSelect options={Object.values(this.axesOrder)} onChange={this.handleAxesOrderChanged} />
+                </FormGroup>
+                <FormGroup inline={true} label={"Keep previous PV Image"}>
+                    <Switch
+                        onChange={event => {
+                            const e = event.target as HTMLInputElement;
+                            this.widgetStore.setKeep(e.checked);
+                            console.log(this.widgetStore.keep);
```
Comment (YuHsuan-Hwang) [inline src/components/PvGenerator/PvGeneratorComponent.tsx]: remove console log

**Review by YuHsuan-Hwang — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
This PR is ready for merge. @crocka Please update the change log, thanks.

**Review by YuHsuan-Hwang — APPROVED** [review]
