### PR TITLE
Kuanchou/2285 devicepixelratio bug

### LINKED ISSUE #2285: Image and region rendering on secondary screen
**Describe the bug**

If we have a running CARTA session on one screen (eg MacBook Pro, deviceRatio=1) and move the browser window to the secondary screen (eg 27" 4K, deviceRatio=1), image and region rendering will be abnormal. Zoom/pan image is abnormal too. The issue happens as long as the deviceRatio changes for a living session.

**To Reproduce**
1. on a Retina display, have an image loaded and create some regions
2. move the browser to another screen (non-retina)
3. try to zoom/pan image, move region etc to see the issue

**Expected behavior**
Regarding less the changing deviceRatio, image/region rendering and image pan/zoom should be still normal.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: electron / chrome / firefox / safari
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v4-stable
 - Frontend branch [e.g. dev, v3b2 release]: dev, v4-stable

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

Close #2285. The different devicePixelRatio between Retina and non-Retina monitors causes the components in the image viewer to not properly show. Fix the bug by listening for devicePixelRatio when it changes. 

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [ ] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [ ] ~user manual prepared (for large new features)~

### CODE REVIEW

File: src/stores/AppStore/AppStore.ts [hunk 1]
```diff
@@ -2108,6 +2111,34 @@ export class AppStore {
...
+            const mqString = `(resolution: ${window.devicePixelRatio}dppx)`;
+            const media = matchMedia(mqString);
+            media.addEventListener("change", updatePixelRatio);
+            remove = () => {
+                media.removeEventListener("change", updatePixelRatio);
+            };
+
+            this.pixelRatio.previous = this.pixelRatio.current;
+            this.pixelRatio.current = devicePixelRatio;
+            this.handleInvariantImageSize();
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: Wonder if we could set `window.devicePixelRatio` and (unupdated) `pixelRatio.current` as inputs for `handleInvariantImageSize`, so that we don't need to store `pixeRatio.previous`.

File: src/stores/AppStore/AppStore.ts [hunk 2]
```diff
@@ -2108,6 +2111,34 @@ export class AppStore {
...
+                remove();
+            }
+            const mqString = `(resolution: ${window.devicePixelRatio}dppx)`;
+            const media = matchMedia(mqString);
+            media.addEventListener("change", updatePixelRatio);
+            remove = () => {
+                media.removeEventListener("change", updatePixelRatio);
+            };
+
+            this.pixelRatio.previous = this.pixelRatio.current;
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: Do we also consider `imageRatio` here?

File: src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx [hunk 3]
```diff
@@ -281,6 +281,10 @@ export class LineSegmentRegionComponent extends React.Component<LineSegmentRegio
         // eslint-disable-next-line @typescript-eslint/no-unused-vars
         const imageRatio = AppStore.Instance.imageRatio;
 
+        // trigger re-render when changing devicePixelRatio (switching monitor)
+        // eslint-disable-next-line @typescript-eslint/no-unused-vars
+        const pixelRatio = AppStore.Instance.pixelRatio;
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx:283]: We could combine unused variables in a block.

File: src/components/ImageView/RegionView/PointRegionComponent.tsx [hunk 4]
```diff
@@ -69,6 +69,12 @@ export class PointRegionComponent extends React.Component<PointRegionComponentPr
         // eslint-disable-next-line @typescript-eslint/no-unused-vars
         const imageRatio = AppStore.Instance.imageRatio;
 
+        // trigger re-render when changing devicePixelRatio (switching monitor)
+        /* eslint-disable @typescript-eslint/no-unused-vars */
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/PointRegionComponent.tsx:69]: Same comment.

File: src/components/ImageView/RegionView/SimpleShapeRegionComponent.tsx [hunk 5]
```diff
@@ -567,6 +567,12 @@ export class SimpleShapeRegionComponent extends React.Component<SimpleShapeRegio
         // eslint-disable-next-line @typescript-eslint/no-unused-vars
         const imageRatio = AppStore.Instance.imageRatio;
 
+        // trigger re-render when changing devicePixelRatio (switching monitor)
+        /* eslint-disable @typescript-eslint/no-unused-vars */
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/SimpleShapeRegionComponent.tsx:567]: Same comment.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
Thanks for fixing this important issue! 👍

File: src/stores/AppStore/AppStore.ts (hunk 2 above)
Comment (YuHsuan-Hwang) [reply src/stores/AppStore/AppStore.ts]: @loveluthien We also need actions for updating observables.

Comment (loveluthien) [reply src/stores/AppStore/AppStore.ts]: I multiply imageRatio in frameStore to avoid fov problem when export high resolution png

File: CHANGELOG.md [hunk 6]
```diff
@@ -32,6 +32,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * Fixed the catalog load button status after double clicking catalog files ([#2378](https://github.com/CARTAvis/carta-frontend/issues/2378)).
 * Synchronized the value format in the pan and zoom tab in the image view settings widget ([#2235](https://github.com/CARTAvis/carta-frontend/issues/2235)).
 * Fix save image/export regions bug which could cause directory overwrite or deletion ([#1377](https://github.com/CARTAvis/carta-backend/issues/1377)).
+* Fix incorrect rendering of image view when moving the window from Retina to non-Retina monitor, and vice versa ([[#2285](https://github.com/CARTAvis/carta-frontend/issues/2285)])
```
Comment (YuHsuan-Hwang) [inline CHANGELOG.md]: Perhaps we can make it more general: `when moving the window to monitors with different screen resolution.`

File: src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx [hunk 7]
```diff
@@ -277,9 +277,11 @@ export class LineSegmentRegionComponent extends React.Component<LineSegmentRegio
         let anchors = null;
         let newAnchor = null;
         let pointArray: Array<number>;
-        // trigger re-render when exporting images
-        // eslint-disable-next-line @typescript-eslint/no-unused-vars
+        // trigger re-render when exporting images and changing devicePixelRatio (switching monitor)
+        /* eslint-disable @typescript-eslint/no-unused-vars */
         const imageRatio = AppStore.Instance.imageRatio;
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx:280]: Since `pixelRatio` changes with `imageRatio`, we could remove this line.

File: src/components/ImageView/RegionView/PointRegionComponent.tsx [hunk 8]
```diff
@@ -65,9 +65,12 @@ export class PointRegionComponent extends React.Component<PointRegionComponentPr
         let centerPixelSpace: Point2D;
         let rotation: number;
 
-        // trigger re-render when exporting images
-        // eslint-disable-next-line @typescript-eslint/no-unused-vars
+        // trigger re-render when exporting images and  changing devicePixelRatio (switching monitor)
+        /* eslint-disable @typescript-eslint/no-unused-vars */
         const imageRatio = AppStore.Instance.imageRatio;
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/PointRegionComponent.tsx]: Same comment.

File: src/components/ImageView/RegionView/SimpleShapeRegionComponent.tsx [hunk 9]
```diff
@@ -563,9 +563,12 @@ export class SimpleShapeRegionComponent extends React.Component<SimpleShapeRegio
         let shapeNode: React.ReactNode;
         const centerReferenceImage = region.center;
 
-        // trigger re-render when exporting images
-        // eslint-disable-next-line @typescript-eslint/no-unused-vars
+        // trigger re-render when exporting images and changing devicePixelRatio (switching monitor)
+        /* eslint-disable @typescript-eslint/no-unused-vars */
         const imageRatio = AppStore.Instance.imageRatio;
```
Comment (YuHsuan-Hwang) [inline src/components/ImageView/RegionView/SimpleShapeRegionComponent.tsx]: Same comment.

File: src/stores/AppStore/AppStore.ts [hunk 10]
```diff
@@ -513,6 +514,10 @@ export class AppStore {
         return frameMap;
     }
 
+    @computed get pixelRatio(): number {
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts:520]: Would be helpful to add documentation here.

File: src/stores/AppStore/AppStore.ts [hunk 11]
```diff
@@ -2108,6 +2115,38 @@ export class AppStore {
...
+                media.removeEventListener("change", updatePixelRatio);
+            };
+
+            this.handleDevicePixelRatioChange(this.devicePixelRatio);
+        };
+        updatePixelRatio();
+    }
+
+    // update devicePixelRatio and make the image size invariant on screen
+    @action private handleDevicePixelRatioChange(prevPixelRatio: number) {
```
Comment (YuHsuan-Hwang) [inline src/stores/AppStore/AppStore.ts]: Perhaps we should rename `prevPixelRatio` to `prevDevicePixelRatio` to be clear that it is not "previous `this.pixelRatio`."

File: src/stores/ImageFittingStore/ImageFittingStore.ts [hunk 12]
```diff
@@ -383,9 +383,9 @@ export class ImageFittingStore {
         let rotation = 0;
         const baseFrame = frame.spatialReference ?? frame;
         let center = baseFrame.center;
-        const pixelRatio = baseFrame.renderHiDPI ? devicePixelRatio * AppStore.Instance.imageRatio : 1.0;
-        const imageWidth = (pixelRatio * baseFrame.renderWidth) / baseFrame.zoomLevel / baseFrame.aspectRatio;
-        const imageHeight = (pixelRatio * baseFrame.renderHeight) / baseFrame.zoomLevel;
+        // const pixelRatio = devicePixelRatio * AppStore.Instance.imageRatio;
```
Comment (YuHsuan-Hwang) [inline src/stores/ImageFittingStore/ImageFittingStore.ts]: Remove comment.

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
The new refactoring looks good.

File: src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx (hunk 7 above)
Comment (loveluthien) [reply src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx:280]: this imageRatio is used later, so I move it out.

Comment (YuHsuan-Hwang) [reply src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx:280]: ok.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]
@loveluthien excellent fix to the usability! e2e tests are all passing and manual tests are looking good. 👍
