### PR TITLE
replace regions with elements in export dialog and fix selected numbers

### LINKED ISSUE #2297: A proper word to represent both region and annotation in the export dialog
**Describe the bug**

As reported in [here](https://github.com/CARTAvis/carta-frontend/pull/2283#pullrequestreview-1746304763) (see append image), we need to replace word "region" with a proper term that is generic for region and annotation.

**To Reproduce**
1. Create regions and annotations
2. Click "Export all regions" button.
3. See the content in the right panel.

**Expected behavior**
Proper word to represent both region and annotation.

**Screenshots or videos**

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura, ubuntu
 - Browser [e.g. chrome, safari, electron app]: 
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v4-stable, dev
 - Frontend branch [e.g. dev, v3b2 release]: v4-stable, dev

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

This PR closes #2297. The bug is that the selected region/annotation number doesn't update when deleting them if the export dialog is opened. This bug also makes export not function if any region is deleted during an opened export dialog. 

This bug is because the exporting region list is only updated once when opening the export dialog. We now update the list when the region/annotation object is deleted.

Test:
- fix the bug.
- adding or deleting regions will keep the checked export regions.
- replace "regions" with "elements" in the export dialog.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] changelog updated / no changelog update needed
- [x] unit test added (for functions with no dependenies)
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] user manual prepared (for large new features)

### CODE REVIEW

File: src/stores/Frame/Region/RegionSetStore.ts [hunk 1]
```diff
@@ -293,12 +293,17 @@ export class RegionSetStore {
...
+        let exportRegionIndexes: number[] = [];
         // Cursor region cannot be deleted
         if (region && region.regionId !== CURSOR_REGION_ID && this.regions.length) {
             if (region === this.selectedRegion) {
                 this.selectedRegion = this.regions[0];
             }
             this.regions = this.regions.filter(r => r !== region);
+            this.regions.forEach((region, index) => {
+                if (region.regionId !== CURSOR_REGION_ID) exportRegionIndexes.push(index);
+            });
```
Comment (YuHsuan-Hwang) [inline src/stores/Frame/Region/RegionSetStore.ts]: Could we simplify it with `filter` and `map`?

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good. 👍

**Review by kswang1029 — APPROVED** [review]
looks good~

File: src/stores/Frame/Region/RegionSetStore.ts [hunk 2]
```diff
@@ -298,6 +298,9 @@ export class RegionSetStore {
             if (region === this.selectedRegion) {
                 this.selectedRegion = this.regions[0];
             }
+            const selectedInd = this.regions.findIndex(r => r === region);
+            let exportRegionIndexes = FileBrowserStore.Instance.exportRegionIndexes.filter(x => x !== selectedInd).map(x => (x > selectedInd ? x - 1 : x));
```
Comment (crocka) [inline src/stores/Frame/Region/RegionSetStore.ts:302]: do we need to update the deleteExportRegionIndex function in the FileBrowserStore, so that some indexes are reduced by 1?

Comment (loveluthien) [reply src/stores/Frame/Region/RegionSetStore.ts:302]: No. If I understand correctly. The deleteExportRegionIndex function is to unselect export regions, and the regions still exist. In the current structure, there is no need to reduce some indexes by 1 when unselecting the exporting regions.

Comment (YuHsuan-Hwang) [reply src/stores/Frame/Region/RegionSetStore.ts:302]: Looks like we don't need to adjust deleteExportRegionIndex.

**Review by crocka — APPROVED** [review]
