### PR TITLE
Fix keyboard shortcuts of next/previous images

### LINKED ISSUE #758: keyboard event conflict between image viewer and drop down menu
reproduce:
(http://carta.asiaa.sinica.edu.tw/frontend/3f0c72e/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev)
1. open a file with z coordinate
2. open spectral profiler setting panel, choose a coordinate through drop down(set focus to drop down)
3. press F repeatedly, then image viewer will freeze/unfreeze and dropdown in setting panel will go through the F-started options repeatedly as well because the dropdown also get the F keyboard event

### LINKED ISSUE #2575: Next / previous image keyboard shortcuts not working
**Describe the bug**

Next / previous image keyboard shortcuts aren't working on macOS (Sequoia 15.5, M4 chip). 

**To Reproduce**

Load two images, apply try to switch between them with the keyboard shortcuts.

**Expected behavior**

Images should switch when keyboard shortcuts are activated.

**Platform info (please complete the following information):**

macOS, Sequoia 15.5
Problem is with standalone CARTA app, but also persists with Firefox 140.0.4 (aarch64)
CARTA 5.0.3 (31 July 2025)

### PR DESCRIPTION
**Pull request by izkgao**
**Description**

Closes #2575 and closes #758.

Fixed:

1. Fix keyboard shortcuts of next/previous images
2. Migrate from Blueprint `HotkeysTarget` to hook-based `useHotkeys` with a new registrar component.
3. Introduce `HotkeyService` (custom dialog UI + responsive layout) and `HotkeysRegistrar` (global registration + Shift+? handler).
4. Ensure all React roots (including GoldenLayout-created) are wrapped with `HotkeysProvider` to fix “useHotkeys() was used outside of a HotkeysProvider context”.
5. Minor MobX fix: perform selectedStokes reset within an action in Spatial Profile store.
6. Avoid conflicts between keyboard events in the image viewer and the dropdown menu.
7. Add global error suppression for ResizeObserver errors according to [https://github.com/radix-ui/primitives/issues/2313#issuecomment-1986338145](https://github.com/radix-ui/primitives/issues/2313#issuecomment-1986338145).
- How to reproduce:
  - Comment out Line 104-126 (added by this PR) of `public/index.html`
  - Open DevTools (F12)
  - Resize the viewport width to 622px (or try other numbers if the error does not show)
  - Move the cursor to the Histogram Widget button in the upper right corner
  - See errors: ResizeObserver loop completed with undelivered notifications.
- This occurs in this PR only if error suppression is not applied.
image

8. Use custom hotkeys dialog for shift+?, which previously rendered the one generated by BlueprintJS.
- Before (from BlueprintJS):

image

- After (custom hotkeys dialog):

image

9. Automatically resize hotkeys dialog when viewport width changes (min 1 column, max 3 columns).
- Before:

image

- After:

image
image
image

### Testing Notes
- Verify global shortcuts (e.g., Next/Previous image, channel/stokes navigation, region actions, file actions) work outside inputs and are ignored inside editable fields.
- Confirm Shift+? opens the custom dialog and no BlueprintJS dialog appears.
- Resize window to validate 1/2/3 column layouts and width adjustments for hotkeys dialog.
- Verify #758 does not happen.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [ ] GitHub Project estimate added

For the pull request:
- [ ] reviewers and assignee added
- [ ] GitHub Project estimate added
- [x] changelog updated / ~~no changelog update needed~~
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~~protobuf version bumped~~ / no protobuf version bumped needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] ~~corresponding ICD test fix added (`BackendService` changed)~~ / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

### CODE REVIEW

**Comment by loveluthien** [comment]
- When pressing `Shift + ?`, the shortcuts dialog pops up together with the table shortcut dialog. Mac Electron App v5.0 and dev doesn't have this issue. 
- `alt + '` and `alt + "` for next and previous image don't work. Maybe we can remove them?

**Comment by izkgao** [comment]
I initially added `HotkeysProvider` in this PR trying to fix some hotkeys warnings, but later realized it should not be included here, so I now removed it. The issue where `Shift + ?` opened two dialogs was actually caused by `HotkeysProvider`. After removing it, the shortcut `Shift + ?` now behaves normally.

`alt + '` `and alt + "` are added as replacements for `option + ]` and `option + [` on macOS. Without these alternative shortcuts, switching to the next or previous image is not possible on Mac. The reason for using ' and " is that pressing Option + ] and Option + [ on macOS produces ‘ and “ as outputs.

**Comment by izkgao** [comment]
Now BlueprintJS warnings related to hotkeys are solved with no hotkeys dialogs from BlueprintJS table2 popping up when pressing shift + ?.

**Comment by izkgao** [comment]
I used a global event handler to manage Option + ] and Option + [ for the English input method, ensuring that the hotkeys function on Mac. Additionally, the shortcuts do not appear in the hotkeys dialog.

**Comment by izkgao** [comment]
- Migrate from Blueprint `HotkeysTarget` to hook-based `useHotkeys` with a new registrar component.
- Introduce `HotkeyService` (custom dialog UI + responsive layout) and `HotkeysRegistrar` (global registration + Shift+? handler).

File: src/HotkeyWrapper.tsx [hunk 1]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
+            {combo: "shift + d", label: "Toggle light/dark theme", onKeyDown: HotkeyService.ToggleDarkTheme},
+            {combo: "f", label: "Freeze/unfreeze cursor position", onKeyDown: appStore.toggleCursorFrozen},
+            {combo: "g", label: "Mirror cursor on multipanel view", onKeyDown: appStore.toggleCursorMirror}
+        ];
+        return items.map(item => ({...base, ...item}));
+    }
+
+    // For display in custom hotkeys dialog
+    static GetHotkeyDefinitionsForDisplay() {
+        const toElements = (hotkeys: any[]) => hotkeys.map((hotkey, index) => <Hotkey key={index} group={hotkey.group} global={hotkey.global} combo={hotkey.combo} label={hotkey.label} onKeyDown={hotkey.onKeyDown} />);
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: for reading purpose:
const toElements = (hotkeys: any[]) => {
    return hotkeys.map((hotkey, index) => {
        return <Hotkey key={index} group={hotkey.group} global={hotkey.global} combo={hotkey.combo} label={hotkey.label} onKeyDown={hotkey.onKeyDown} />;
    });
};

File: src/HotkeyWrapper.tsx [hunk 2]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
         }
     };
 
-    static RenderHotkeys() {
-        const appStore = AppStore.Instance;
-        const modString = appStore.modifierString;
+    // For display in custom hotkeys dialog
+    static GetNavigationDisplayOnlyHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: It's not a getter, so we can remove Get from the name. Maybe only is redundant.
GetNavigationDisplayOnlyHotkeys -> NavigationDisplayHotkeys

File: src/HotkeyWrapper.tsx [hunk 3]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
-        const fileGroupTitle = "4) File controls";
-        const otherGroupTitle = "5) Other";
-
-        const navigationHotKeys = [
-            <Hotkey key={0} group={navigationGroupTitle} global={true} combo="click" label="Pan image" />,
-            <Hotkey key={1} group={navigationGroupTitle} global={true} combo="middle-click" label="Pan image (inside region)" />,
-            <Hotkey key={2} group={navigationGroupTitle} global={true} combo="mod+click" label="Pan image (inside region)" />,
-            <Hotkey key={3} group={navigationGroupTitle} global={true} combo="mouse-wheel" label="Zoom image" />
+    // For display in custom hotkeys dialog
+    static GetRegionDisplayOnlyHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 4]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
-            <Hotkey key={2} group={regionGroupTitle} global={true} combo="shift + l" label="Unlock all regions" onKeyDown={HotkeyContainer.UnlockAllRegions} />,
-            <Hotkey key={3} group={regionGroupTitle} global={true} combo="del" label="Delete selected region" onKeyDown={appStore.deleteSelectedRegion} />,
-            <Hotkey key={4} group={regionGroupTitle} global={true} combo="backspace" label="Delete selected region" onKeyDown={appStore.deleteSelectedRegion} />,
-            <Hotkey key={5} group={regionGroupTitle} global={true} combo="esc" label="Deselect region/Cancel region creation" onKeyDown={HotkeyContainer.HandleRegionEsc} />,
-            <Hotkey key={6} group={regionGroupTitle} global={true} combo="mod" label="Switch region creation mode" />,
-            <Hotkey key={7} group={regionGroupTitle} global={true} combo={"shift"} label="Symmetric region creation" />,
-            <Hotkey key={8} group={regionGroupTitle} global={true} combo="double-click" label="Region properties" />
+    static GetRegionHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 5]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
+    }
 
-        const animatorHotkeys = [
-            <Hotkey key={0} group={animatorGroupTitle} global={true} combo={`${modString}]`} label="Next image" onKeyDown={appStore.nextImage} />,
-            <Hotkey key={1} group={animatorGroupTitle} global={true} combo={`${modString}[`} label="Previous image" onKeyDown={appStore.prevImage} />,
-            <Hotkey key={2} group={animatorGroupTitle} global={true} combo={`${modString}up`} label="Next channel" onKeyDown={HotkeyContainer.NextChannel} />,
-            <Hotkey key={3} group={animatorGroupTitle} global={true} combo={`${modString}down`} label="Previous channel" onKeyDown={HotkeyContainer.PrevChannel} />,
-            <Hotkey key={4} group={animatorGroupTitle} global={true} combo={`${modString}shift + up`} label="Next Stokes cube" onKeyDown={HotkeyContainer.NextStokes} />,
-            <Hotkey key={5} group={animatorGroupTitle} global={true} combo={`${modString}shift + down`} label="Previous Stokes cube" onKeyDown={HotkeyContainer.PrevStokes} />
+    static GetFrameControlHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 6]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
-            <Hotkey key={1} group={fileGroupTitle} global={true} combo={`${modString}L`} label="Append image" onKeyDown={() => appStore.fileBrowserStore.showFileBrowser(BrowserMode.File, true)} />,
-            <Hotkey key={2} group={fileGroupTitle} global={true} combo={`${modString}W`} label="Close image" onKeyDown={() => appStore.closeCurrentFile(true)} />,
-            <Hotkey key={3} group={fileGroupTitle} global={true} combo={`${modString}S`} label="Save image" onKeyDown={() => appStore.fileBrowserStore.showFileBrowser(BrowserMode.SaveFile, false)} />,
-            <Hotkey key={4} group={fileGroupTitle} global={true} combo={`${modString}G`} label="Import catalog" onKeyDown={() => appStore.fileBrowserStore.showFileBrowser(BrowserMode.Catalog, false)} />,
-            <Hotkey key={5} group={fileGroupTitle} global={true} combo={`${modString}E`} label="Export image" onKeyDown={() => appStore.exportImage(1)} />
+    // Hidden hotkeys for input method compatibility
+    static GetFrameControlHiddenHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 7]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
+            {combo: `${modString}“`, label: "Previous image", onKeyDown: appStore.prevImage}
         ];
+        return items.map(item => ({...base, ...item}));
+    }
 
-        const otherHotKeys = [
-            <Hotkey key={0} group={otherGroupTitle} global={true} combo="shift + D" label="Toggle light/dark theme" onKeyDown={HotkeyContainer.ToggleDarkTheme} />,
-            <Hotkey key={1} group={otherGroupTitle} global={true} combo="F" label="Freeze/unfreeze cursor position" onKeyDown={appStore.toggleCursorFrozen} />,
-            <Hotkey key={2} group={otherGroupTitle} global={true} combo="G" label="Mirror cursor on multipanel view" onKeyDown={appStore.toggleCursorMirror} />
+    static GetFileControlHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 8]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
...
-        return (
-            <Hotkeys>
-                {regionHotKeys}
-                {navigationHotKeys}
-                {animatorHotkeys}
-                {fileHotkeys}
-                {otherHotKeys}
-            </Hotkeys>
-        );
+    static GetOtherHotkeys() {
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: Same comment

File: src/HotkeyWrapper.tsx [hunk 9]
```diff
@@ -108,72 +109,176 @@ export class HotkeyContainer extends React.Component {
         }
     };
 
-    static RenderHotkeys() {
-        const appStore = AppStore.Instance;
-        const modString = appStore.modifierString;
+    // For display in custom hotkeys dialog
+    static GetNavigationDisplayOnlyHotkeys() {
+        const group = "1) Navigation";
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: we can have an enum for "1) Navigation", "2) Regions"...

File: src/HotkeyWrapper.scss [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+$col-w: 360px; /* column width */
+$gap: 20px; /* column gap */
+$pad: 20px; /* Blueprint dialog body horizontal padding per side */
+$breakpoint-buffer: 100px; /* additional buffer for responsive breakpoint calculations */
+
+// Calculate breakpoint values
+$breakpoint-2col: $col-w * 2 + $gap + $pad * 2 + $breakpoint-buffer;
+$breakpoint-3col: $col-w * 3 + $gap * 2 + $pad * 2 + $breakpoint-buffer;
+
+.bp5-dialog.hotkeys-dialog {
```
Comment (loveluthien) [inline src/HotkeyWrapper.scss]: use #{$ns} for bp5

File: CHANGELOG.md [hunk 11]
```diff
@@ -10,6 +10,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * Disable text selection in file browser ([#2574](https://github.com/CARTAvis/carta-frontend/issues/2574)).
 * Fixed VizieR database query ([#2480](https://github.com/CARTAvis/carta-frontend/issues/2480)).
 * Fixed an issue where the PV generator widget and progress bar did not appear when creating a new PV image while another PV image was already open ([#2349](https://github.com/CARTAvis/carta-frontend/issues/2349)).
+* Fixed hotkeys for navigating to the next and previous images, resolved keyboard event conflicts between the image viewer and the dropdown menu, and automatically resized the hotkeys dialog ([#2575](https://github.com/CARTAvis/carta-frontend/issues/2575), [#758](https://github.com/CARTAvis/carta-frontend/issues/758)).
```
Comment (loveluthien) [inline CHANGELOG.md]: Fixed hotkeys of the next and previous images for macOS and resolved keyboard event conflicts between the image viewer and the dropdown menu.

### Changed
* Changed layout of Control and Shortcuts dialog ([new issue?])

**Review by loveluthien — APPROVED** [review]
😎

File: src/HotkeyWrapper.tsx [hunk 12]
```diff
@@ -108,72 +117,176 @@ export class HotkeyContainer extends React.Component {
...
+    }
+
+    // For display in custom hotkeys dialog
+    static GetHotkeyDefinitionsForDisplay() {
+        const toElements = (hotkeys: any[]) =>
+            hotkeys.map((hotkey, index) => {
+                return <Hotkey key={index} group={hotkey.group} global={hotkey.global} combo={hotkey.combo} label={hotkey.label} onKeyDown={hotkey.onKeyDown} />;
+            });
+
+        // 1) Navigation
```
Comment (loveluthien) [inline src/HotkeyWrapper.tsx]: remove number here

**Review by kswang1029 — APPROVED** [review]
overall this looks fine on macOS and Ubuntu. 👍
