### PR TITLE
carli/2135_image_position_in_fixed_grid_size

### LINKED ISSUE #2135: image positioning with fixed grid size
**Describe the bug**
Apologies not picking this up while testing the feature. 

When we set the multiple-panel mode to fixed grid size, the reminder images are not placed correctly at the grid positions. In the screenshot, we see the two orange images are placed in the incorrect locations.
Screen Shot 2023-04-06 at 10 21 58

They should be placed  in the magenta grids as follows
Screen Shot 2023-04-06 at 10 21 58 copy

The other empty grids are in green in this case (fixed 3x3).

**To Reproduce**
1. load five images
2. go to the image viewer settings dialog and set the multi-panel mode to fixed grid size
3. set columns=3 and set rows=3
4. See the position of the last two images for the issue

**Expected behavior**
With fixed grid size mode, reminder images should still be placed at the corresponding grids. (ie in this case, in the magenta grids)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome 
 - Browser version [e.g. 22]: 111
 - Backend branch [e.g. dev, v3b2 release]: dev, v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: dev, v3-stable

### PR DESCRIPTION
**Pull request by crocka**
**Description**

Originally, the gridTemplateRows was not set, only the gridTemplateColumns was set. Adding the gridTemplateRows for ImageViewComponent would fix the problem. Resolves #2135.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] ~~changelog updated~~ / no changelog update needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

File: src/components/ImageView/ImageViewComponent.tsx [hunk 1]
```diff
@@ -225,7 +225,10 @@ export class ImageViewComponent extends React.Component<WidgetProps> {
 
         return (
             <ReactResizeDetector handleWidth handleHeight onResize={this.onResize} refreshMode={"throttle"} refreshRate={33}>
-                <div className="image-view-div" style={{gridTemplateColumns: `repeat(${appStore.numImageColumns}, auto)`}}>
```
Comment (kswang1029) [inline src/components/ImageView/ImageViewComponent.tsx:228]: @crocka are we able to tell when it is "auto", what's the width and height in px?

File: src/components/ImageView/ImageViewComponent.tsx [hunk 2]
```diff
@@ -225,7 +225,10 @@ export class ImageViewComponent extends React.Component<WidgetProps> {
...
+                <div
+                    className="image-view-div"
+                    style={{gridTemplateColumns: `repeat(${appStore.numImageColumns}, ${appStore.overlayStore.viewWidth}px)`, gridTemplateRows: `repeat(${appStore.numImageRows}, ${appStore.overlayStore.viewHeight}px)`}}
```
Comment (kswang1029) [inline src/components/ImageView/ImageViewComponent.tsx]: I am seeing region and contour matching tests failing (apparently the rendered region/contour is off by 1 or 2 screen pixel. Wonder if this is related to the changes here where we explicitly set the width and height in px.

Comment (kswang1029) [reply src/components/ImageView/ImageViewComponent.tsx]: Based on my manual tests, I think region and contours are still rendered at the right places. If this is the case, we will need to revised the e2e tests a bit (we check pixel rgba values at selected positions in the png images). Before we do the test revision, I would like to know the root cause just in case.

**Review by kswang1029 — APPROVED** [review]
This is an important fix for the publication quality export features. 👍 
No regression from e2e tests. Manual tests look good.

**Review by YuHsuan-Hwang — APPROVED** [review]
