### PR TITLE
Prevent spectral profile widget from reverting to original position or size

### LINKED ISSUE #482: floating widget cannot be moved to new location if its content is updating (spectral profile)
To reproduce the issue, launch a floating spectral profile widget and request a region profile that needs some time to get the final profile. When the profile is updating (we see progress % increasing), and if we hold and drag the widget, the widget will restore its original position when a new update comes in.

### PR DESCRIPTION
**Pull request by izkgao**
**Description**

Closes #482.

This PR introduces the following fixes:
1. Prevents the spectral profile widget from reverting to its original position or size.
    - Achieved by detecting changes between `prevConfig` and `currConfig`.
2. Ensures that the height in RND is always equal to widgetConfig.defaultHeight + headerHeight.

**How to test**
1. Open an image with a large number of channels (e.g., > 10,000).
2. Draw a rectangle or point region.
4. Open the spectral profile widget.
5. While the spectral profile is still updating, move and resize the widget.
6. Ensure that the position and size do not revert back to the original ones.

**Additional test**
1. Open a spectral profile widget.
2. Change the size and position of this widget.
3. Save layout.

_Test 1:_
1. Close widget.
2. Apply layout.
3. See the widget shows on the saved position with the saved size.

_Test 2:_
1. Do not close the widget.
2. Change the position and size of the widget.
3. Apply layout.
5. See the widget moves to the saved position with the saved size.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~~no changelog update needed~~
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~~protobuf version bumped~~ / no protobuf version bumped needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] ~~corresponding ICD test fix added (`BackendService` changed)~~ / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

### CODE REVIEW

**Comment by loveluthien** [comment]
I commented out `componentDidMount()`, `onDragStop`, and `onResizeStop`, and everything appears to be fine; the problem is solved. It seems the current `Rnd` has its own way to deal with position and resize. @izkgao, please take a look.

File: src/components/FloatingWidget/FloatingWidgetComponent.tsx [hunk 1]
```diff
@@ -25,19 +25,31 @@ class FloatingWidgetComponentProps {
 
 @observer
 export class FloatingWidgetComponent extends React.Component<FloatingWidgetComponentProps> {
+    private static readonly HEADER_HEIGHT = 25;
```
Comment (loveluthien) [inline src/components/FloatingWidget/FloatingWidgetComponent.tsx]: I realized we adopted multiple naming conventions for `private static readonly`. Maybe we should stick to one style. I suggest using PascalCase which is majority of naming for `private static readonly` in our code base. So, please modify them into `HeaderHeight` and `RootMenuHeight`.

**Review by loveluthien — APPROVED** [review]
😎

**Review by kswang1029 — APPROVED** [review]
looks good. 👍
