### PR TITLE
Fix 1393

### LINKED ISSUE #1393: Profiles broken for images with minimal headers
In the latest development version, images with minimal headers (e.g. the synthetic gaussian images produced by this script) have broken profiles (the cursor is fixed in the middle of the image and moving the cursor does not change the profiles. I suspect that this is connected to the recent axis changes. The affected images produce console warnings like Spectral frame not found and Sky frame not found.

I'm attaching a small zipped sample image which demonstrates the issue: [image-10-10-10.zip](https://github.com/CARTAvis/carta-frontend/files/6272540/image-10-10-10.zip)

I previously filed this as a [backend issue](https://github.com/CARTAvis/carta-backend/issues/789), but today I confirmed that it only occurs when I use the latest frontend. If I use the latest backend version but downgrade to the previous frontend development tag, the bug is not present.

### PR DESCRIPTION
**Pull request by duidae**
closes #1393

### CODE REVIEW

File: wasm_src/ast_wrapper/ast_wrapper.cc [hunk 1]
```diff
@@ -52,6 +52,14 @@ EMSCRIPTEN_KEEPALIVE AstFrameSet* getFrameFromFitsChan(AstFitsChan* fitschan)
         return nullptr;
     }
 
+    // work around for missing CTYPE1 & CTYPE2
+    if (checkSkyDomain) {
+        const char *domain = astGetC(frameSet, "Domain");
+        if (!strstr(domain, "SKY")) {
+            return nullptr;
```
Comment (veggiesaurus) [inline wasm_src/ast_wrapper/ast_wrapper.cc:60]: if we're returning `nullptr` here, we should call `astDelete` first, shouldn't we? otherwise we're leakingWebAssembly  memory

File: wasm_src/ast_wrapper/post.ts [hunk 2]
```diff
@@ -97,7 +97,7 @@ Module.setCanvas = function (canvas) {
 Module.plot = Module.cwrap("plotGrid", "number", ["number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "string"]);
 Module.emptyFitsChan = Module.cwrap("emptyFitsChan", "number");
 Module.putFits = Module.cwrap("putFits", null, ["number", "string"])
-Module.getFrameFromFitsChan = Module.cwrap("getFrameFromFitsChan", "number", ["number"]);
+Module.getFrameFromFitsChan = Module.cwrap("getFrameFromFitsChan", "number", ["number", "boolean"]);
```
Comment (veggiesaurus) [inline wasm_src/ast_wrapper/post.ts]: `cwrap` [only supports ](https://emscripten.org/docs/api_reference/preamble.js.html#cwrap)`number` and `string`. That's why we've used `number` elsewhere.

**Review by veggiesaurus — CHANGES_REQUESTED** [review]

**Comment by veggiesaurus** [comment]
@duidae also a couple of merge conflicts now that #1362 has been merged into `dev`.

**Review by veggiesaurus — APPROVED** [review]
looks ok to me

**Comment by veggiesaurus** [comment]
@kswang1029 can we merge this in?

**Comment by veggiesaurus** [comment]
@confluence can you test with this branch please?

**Review by kswang1029 — APPROVED** [review]

**Comment by duidae** [comment]
@veggiesaurus can I merge this PR?

**Comment by veggiesaurus** [comment]
Ok sure 👍🏼

**Comment by duidae** [comment]
> Ok sure 👍🏼

thank u!
