### PR TITLE
Jason/line disappear

### LINKED ISSUE #1453: spectral line results disappear if filtered rows are too few
reproduce(according to beta user feedback):
1. open spectral line query widget & query with range 230~231 GHz
2. scroll down to row 50
3. input "Monoxide" in chemical name & press filter
4. the info in the bottom shows "Showing 2 filtered lines..." but see nothing

the other way to reproduce:
3. input "Ketene" in chemical name & press filter

image
image

### PR DESCRIPTION
**Pull request by duidae**
closes #1453

### CODE REVIEW

File: src/components/SpectralLineQuery/SpectralLineQueryComponent.tsx [hunk 1]
```diff
@@ -197,12 +197,12 @@ export class SpectralLineQueryComponent extends React.Component<WidgetProps> {
 
     private handleFilter = () => {
         this.widgetStore.filter();
-        this.resultTableRef?.scrollToRegion(Regions.row(0));
+        setTimeout(() => this.resultTableRef?.scrollToRegion(Regions.row(0)), 20);
```
Comment (veggiesaurus) [inline src/components/SpectralLineQuery/SpectralLineQueryComponent.tsx]: @duidae do you think we should use a handle here so that we can `clearTimeout` of the existing scroll instruction?

**Comment by kswang1029** [comment]
The presence of the vertical scrollbar seems delayed by three rows? If there are two rows out of view we cannot scroll down to see those. 

https://user-images.githubusercontent.com/20819712/119917569-662c1a80-bf99-11eb-97ae-739ce1f95fd5.mp4

**Comment by duidae** [comment]
> The presence of the vertical scrollbar seems delayed by three rows? If there are two rows out of view we cannot scroll down to see those.
> 
>  May-28-2021.09-44-17.mp4

there should be some bugs in scroll calculation of BlueprintJS Table, fix with temporary workaround by appending 3 empty rows to ensure that the scroll pops out.

File: src/components/SpectralLineQuery/SpectralLineQueryComponent.tsx (hunk 1 above)
Comment (duidae) [reply src/components/SpectralLineQuery/SpectralLineQueryComponent.tsx]: @veggiesaurus handle added, but the behavior seems the same before/after the timer handle added, a little bit unsure about why we need it?

Comment (veggiesaurus) [reply src/components/SpectralLineQuery/SpectralLineQueryComponent.tsx]: I suppose its not necessary. I was just worried that we would have multiple `handleFilter` functions resetting the scroll to row 0.

**Comment by veggiesaurus** [comment]
> > The presence of the vertical scrollbar seems delayed by three rows? If there are two rows out of view we cannot scroll down to see those.
> > May-28-2021.09-44-17.mp4
> 
> there should be some bugs in scroll calculation of BlueprintJS Table, fix with temporary workaround by appending 3 empty rows to ensure that the scroll pops out.

Yet another reason to attempt a switch to a more readily maintained and lightweight virtualised table package :see_no_evil:

**Review by kswang1029 — APPROVED** [review]
