### PR TITLE
Jason/issue 1413

### LINKED ISSUE #1413: cant save layout with pop-out settings panel from ver. 1.4
reproduce:
1. create a whatever layout & click cog of any widget in order to get the pop-out settings panel
2. save this layout
3. reload frontend, cant see the created layout in layout list

ver. 1.3 ok, bug starts from ver. 1.4
bug1

### LINKED ISSUE #1420: warning keeps poping out while preference layout no longer exists
reproduce:
1. create a custom layout `z`, set `z` to preference layout
2. type `localStorage.removeItem("savedLayouts")` in console to delete saved layout
3. reload frontend, shows `Applying preference layout "z" failed!`
4. set preference layout to `Default` in preference
5. reload frontend, `Applying preference layout "z" failed!` shows again, layout `Default` is not applied.
image

### PR DESCRIPTION
**Pull request by duidae**
closes #1413, closes #1420

### CODE REVIEW

File: src/stores/AppStore.ts [hunk 1]
```diff
@@ -1227,16 +1227,16 @@ export class AppStore {
...
-        // Splash screen mask
         autorun(() => {
             if (this.astReady && this.zfpReady && this.cartaComputeReady && this.apiService.authenticated) {
                 this.preferenceStore.fetchPreferences().then(() => {
                     this.layoutStore.fetchLayouts().then(() => {
                         // Attempt connection after authenticating
                         this.tileService.setCache(this.preferenceStore.gpuTileCache, this.preferenceStore.systemTileCache);
                         if (!this.layoutStore.applyLayout(this.preferenceStore.layout)) {
-                            AlertStore.Instance.showAlert(`Applying preference layout "${this.preferenceStore.layout}" failed!`);
+                            AlertStore.Instance.showAlert(`Applying preference layout "${this.preferenceStore.layout}" failed! Reset preference layout to default.`);
```
Comment (veggiesaurus) [inline src/stores/AppStore.ts]: can you change to "Resetting layout to default."

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
minor text change

**Review by veggiesaurus — APPROVED** [review]
